centers = {
    1: ('Melbourne (WMC)', 'ammc'),
    2: ('Melbourne - BMRC (WMC)', None),
    3: ('Melbourne (WMC)', None),
    4: ('Moscow (WMC)', None),
    5: ('Moscow (WMC)', None),
    6: ('Moscow (WMC)', None),
    7: ('US National Weather Service - NCEP (WMC)', 'kwbc'),
    8: ('US National Weather Service - NWSTG (WMC)', None),
    9: ('US National Weather Service - Other (WMC)', None),
    10: ('Cairo (RSMC/RAFC)', None),
    11: ('Cairo (RSMC/RAFC)', None),
    12: ('Dakar (RSMC/RAFC)', None),
    13: ('Dakar (RSMC/RAFC)', None),
    14: ('Nairobi (RSMC/RAFC)', None),
    15: ('Nairobi (RSMC/RAFC)', None),
    16: ('Casablanca', None),
    17: ('Tunis (RSMC)', None),
    18: ('Tunis-Casablanca (RSMC)', None),
    19: ('Tunis-Casablanca (RSMC)', None),
    20: ('Las Palmas (RAFC)', None),
    21: ('Algiers (RSMC)', None),
    22: ('ACMAD', None),
    23: ('Mozambique (NMC)', None),
    24: ('Pretoria (RSMC)', None),
    25: ('La Reunion (RSMC)', None),
    26: ('Khabarovsk (RSMC)', None),
    27: ('Khabarovsk (RSMC)', None),
    28: ('New Delhi (RSMC/RAFC)', None),
    29: ('New Delhi (RSMC/RAFC)', None),
    30: ('Novosibirsk (RSMC)', None),
    31: ('Novosibirsk (RSMC)', None),
    32: ('Tashkent (RSMC)', None),
    33: ('Jeddah (RSMC)', None),
    34: ('Japanese Meteorological Agency - Tokyo (RSMC)', 'rjtd'),
    35: ('Japanese Meteorological Agency - Tokyo (RSMC)', None),
    36: ('Bankok', None),
    37: ('Ulan Bator', None),
    38: ('Beijing (RSMC)', 'babj'),
    39: ('Beijing (RSMC)', None),
    40: ('Korean Meteorological Administration - Seoul', 'rksl'),
    41: ('Buenos Aires (RSMC/RAFC)', None),
    42: ('Buenos Aires (RSMC/RAFC)', None),
    43: ('Brasilia (RSMC/RAFC)', None),
    44: ('Brasilia (RSMC/RAFC)', None),
    45: ('Santiago', None),
    46: ('Brazilian Space Agency - INPE', 'sbsj'),
    47: ('Columbia (NMC)', None),
    48: ('Ecuador (NMC)', None),
    49: ('Peru (NMC)', None),
    50: ('Venezuela (NMC)', None),
    51: ('Miami (RSMC/RAFC)', None),
    52: ('Tropical Prediction Center (NHC), Miami (RSMC)', None),
    53: ('Canadian Meteorological Service - Montreal (RSMC)', None),
    54: ('Canadian Meteorological Service - Montreal (RSMC)', 'cwao'),
    55: ('San Francisco', None),
    56: ('ARINC Center', None),
    57: ('U.S. Air Force - Global Weather Center', None),
    58: ('US Navy - Fleet Numerical Oceanography Center', 'fnmo'),
    59: ('NOAA Forecast Systems Lab, Boulder CO', None),
    60: ('National Center for Atmospheric Research (NCAR), Boulder, CO', None),
    61: ('Service ARGOS - Landover, MD, USA', None),
    62: ('US Naval Oceanographic Office', None),
    63: ('Reserved', None),
    64: ('Honolulu', None),
    65: ('Darwin (RSMC)', None),
    66: ('Darwin (RSMC)', None),
    67: ('Melbourne (RSMC)', None),
    68: ('Reserved', None),
    69: ('Wellington (RSMC/RAFC)', None),
    70: ('Wellington (RSMC/RAFC)', None),
    71: ('Nadi (RSMC)', None),
    72: ('Singapore', None),
    73: ('Malaysia (NMC)', None),
    74: ('U.K. Met Office - Exeter (RSMC)', 'egrr'),
    75: ('U.K. Met Office - Exeter (RSMC)', None),
    76: ('Moscow (RSMC/RAFC)', None),
    77: ('Reserved', None),
    78: ('Offenbach (RSMC)', 'edzw'),
    79: ('Offenbach (RSMC)', None),
    80: ('Rome (RSMC)', 'cnmc'),
    81: ('Rome (RSMC)', None),
    82: ('Norrkoping', None),
    83: ('Norrkoping', None),
    84: ('French Weather Service - Toulouse', 'lfpw'),
    85: ('French Weather Service - Toulouse', 'lfpw'),
    86: ('Helsinki', None),
    87: ('Belgrade', None),
    88: ('Oslo', None),
    89: ('Prague', None),
    90: ('Episkopi', None),
    91: ('Ankara', None),
    92: ('Frankfurt/Main (RAFC)', None),
    93: ('London (WAFC)', None),
    94: ('Copenhagen', None),
    95: ('Rota', None),
    96: ('Athens', None),
    97: ('European Space Agency (ESA)', None),
    98: ('European Center for Medium-Range Weather Forecasts (RSMC)', 'ecmf'),
    99: ('De BiltNone), Netherlands', None),
    100: ('Brazzaville', None),
    101: ('Abidjan', None),
    102: ('Libyan Arab Jamahiriya (NMC)', None),
    103: ('Madagascar (NMC)', None),
    104: ('Mauritius (NMC)', None),
    105: ('Niger (NMC)', None),
    106: ('Seychelles (NMC)', None),
    107: ('Uganda (NMC)', None),
    108: ('Tanzania (NMC)', None),
    109: ('Zimbabwe (NMC)', None),
    110: ('Hong-Kong', None),
    111: ('Afghanistan (NMC)', None),
    112: ('Bahrain (NMC)', None),
    113: ('Bangladesh (NMC)', None),
    114: ('Bhutan (NMC)', None),
    115: ('Cambodia (NMC)', None),
    116: ("Democratic People's Republic of Korea (NMC)", None),
    117: ('Islamic Republic of Iran (NMC)', None),
    118: ('Iraq (NMC)', None),
    119: ('Kazakhstan (NMC)', None),
    120: ('Kuwait (NMC)', None),
    121: ('Kyrgyz Republic (NMC)', None),
    122: ("Lao People's Democratic Republic (NMC)", None),
    123: ('MacaoNone), China', None),
    124: ('Maldives (NMC)', None),
    125: ('Myanmar (NMC)', None),
    126: ('Nepal (NMC)', None),
    127: ('Oman (NMC)', None),
    128: ('Pakistan (NMC)', None),
    129: ('Qatar (NMC)', None),
    130: ('Republic of Yemen (NMC)', None),
    131: ('Sri Lanka (NMC)', None),
    132: ('Tajikistan (NMC)', None),
    133: ('Turkmenistan (NMC)', None),
    134: ('United Arab Emirates (NMC)', None),
    135: ('Uzbekistan (NMC)', None),
    136: ('Socialist Republic of Viet Nam (NMC)', None),
    137: ('Reserved', None),
    138: ('Reserved', None),
    139: ('Reserved', None),
    140: ('Bolivia (NMC)', None),
    141: ('Guyana (NMC)', None),
    142: ('Paraguay (NMC)', None),
    143: ('Suriname (NMC)', None),
    144: ('Uruguay (NMC)', None),
    145: ('French Guyana', None),
    146: ('Brazilian Navy Hydrographic Center', None),
    147: ('Reserved', None),
    148: ('Reserved', None),
    149: ('Reserved', None),
    150: ('Antigua and Barbuda (NMC)', None),
    151: ('Bahamas (NMC)', None),
    152: ('Barbados (NMC)', None),
    153: ('Belize (NMC)', None),
    154: ('British Caribbean Territories Center', None),
    155: ('San Jose', None),
    156: ('Cuba (NMC)', None),
    157: ('Dominica (NMC)', None),
    158: ('Dominican Republic (NMC)', None),
    159: ('El Salvador (NMC)', None),
    160: ('US NOAA/NESDIS', None),
    161: ('US NOAA Office of Oceanic and Atmospheric Research', None),
    162: ('Guatemala (NMC)', None),
    163: ('Haiti (NMC)', None),
    164: ('Honduras (NMC)', None),
    165: ('Jamaica (NMC)', None),
    166: ('Mexico', None),
    167: ('Netherlands Antilles and Aruba (NMC)', None),
    168: ('Nicaragua (NMC)', None),
    169: ('Panama (NMC)', None),
    170: ('Saint Lucia (NMC)', None),
    171: ('Trinidad and Tobago (NMC)', None),
    172: ('French Departments', None),
    173: ('Reserved', None),
    174: ('Reserved', None),
    175: ('Reserved', None),
    176: ('Reserved', None),
    177: ('Reserved', None),
    178: ('Reserved', None),
    179: ('Reserved', None),
    180: ('Reserved', None),
    181: ('Reserved', None),
    182: ('Reserved', None),
    183: ('Reserved', None),
    184: ('Reserved', None),
    185: ('Reserved', None),
    186: ('Reserved', None),
    187: ('Reserved', None),
    188: ('Reserved', None),
    189: ('Reserved', None),
    190: ('Cook Islands (NMC)', None),
    191: ('French Polynesia (NMC)', None),
    192: ('Tonga (NMC)', None),
    193: ('Vanuatu (NMC)', None),
    194: ('Brunei (NMC)', None),
    195: ('Indonesia (NMC)', None),
    196: ('Kiribati (NMC)', None),
    197: ('Federated States of Micronesia (NMC)', None),
    198: ('New Caledonia (NMC)', None),
    199: ('Niue', None),
    200: ('Papua New Guinea (NMC)', None),
    201: ('Philippines (NMC)', None),
    202: ('Samoa (NMC)', None),
    203: ('Solomon Islands (NMC)', None),
    204: ('Reserved', None),
    205: ('Reserved', None),
    206: ('Reserved', None),
    207: ('Reserved', None),
    208: ('Reserved', None),
    209: ('Reserved', None),
    210: ('Frascati', None),
    211: ('Lanion', None),
    212: ('Lisboa', None),
    213: ('Reykjavik', None),
    214: ('Madrid', 'lemm'),
    215: ('Zurich', None),
    216: ('Service ARGOS - ToulouseNone), FR', None),
    217: ('Bratislava', None),
    218: ('Budapest', None),
    219: ('Ljubljana', None),
    220: ('Warsaw', None),
    221: ('Zagreb', None),
    222: ('Albania (NMC)', None),
    223: ('Armenia (NMC)', None),
    224: ('Austria (NMC)', None),
    225: ('Azerbaijan (NMC)', None),
    226: ('Belarus (NMC)', None),
    227: ('Belgium (NMC)', None),
    228: ('Bosnia and Herzegovina (NMC)', None),
    229: ('Bulgaria (NMC)', None),
    230: ('Cyprus (NMC)', None),
    231: ('Estonia (NMC)', None),
    232: ('Georgia (NMC)', None),
    233: ('Dublin', None),
    234: ('Israel (NMC)', None),
    235: ('Jordan (NMC)', None),
    236: ('Latvia (NMC)', None),
    237: ('Lebanon (NMC)', None),
    238: ('Lithuania (NMC)', None),
    239: ('Luxembourg', None),
    240: ('Malta (NMC)', None),
    241: ('Monaco', None),
    242: ('Romania (NMC)', None),
    243: ('Syrian Arab Republic (NMC)', None),
    244: ('The former Yugoslav Republic of Macedonia (NMC)', None),
    245: ('Ukraine (NMC)', None),
    246: ('Republic of Moldova', None),
    247: ('Reserved', None),
    248: ('Reserved', None),
    249: ('Reserved', None),
    250: ('Reserved', None),
    251: ('Reserved', None),
    252: ('Reserved', None),
    253: ('Reserved', None),
    254: ('EUMETSAT Operations Center', None),
    255: ('Missing Value', None)
}

table4 = {}
