# coding: utf-8

"""
    AristaFlowREST/WorklistManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_worklist_manager
from af_worklist_manager.models.client_worklist_sse_callback_data import ClientWorklistSseCallbackData  # noqa: E501
from af_worklist_manager.rest import ApiException


class TestClientWorklistSseCallbackData(unittest.TestCase):
    """ClientWorklistSseCallbackData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientWorklistSseCallbackData(self):
        """Test ClientWorklistSseCallbackData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_worklist_manager.models.client_worklist_sse_callback_data.ClientWorklistSseCallbackData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
