
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-23T20:25:13+0900",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfe5cfd7f7e77c9245912a6e0432ac411615bdb5",
 "version": "0.3.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
