# Generated by Django 3.1.4 on 2020-12-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_irs_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='statuses_allowed',
            field=models.ManyToManyField(to='oebl_irs_workflow.LemmaStatus'),
        ),
        migrations.AddField(
            model_name='issuelemma',
            name='labels',
            field=models.ManyToManyField(to='oebl_irs_workflow.LemmaLabel'),
        ),
        migrations.AddField(
            model_name='lemma',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
