# Generated by Django 3.1.4 on 2020-12-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oebl_irs_workflow', '0004_auto_20201216_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuelemma',
            name='labels',
            field=models.ManyToManyField(blank=True, to='oebl_irs_workflow.LemmaLabel'),
        ),
    ]
