
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-20T17:04:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc72c6ab38d924a774231a9daaf494f7e5fed502",
 "version": "0.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
