# coding: utf-8

"""
    AristaFlowREST/ExecutionManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConsistencyCheckResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'incons_found': 'bool',
        'status': 'str'
    }

    attribute_map = {
        'incons_found': 'inconsFound',
        'status': 'status'
    }

    def __init__(self, incons_found=None, status=None):  # noqa: E501
        """ConsistencyCheckResponse - a model defined in Swagger"""  # noqa: E501
        self._incons_found = None
        self._status = None
        if not(hasattr(self, "discriminator")) or not(self.discriminator):
            self.discriminator = None
        self.incons_found = incons_found
        self.status = status

    @property
    def incons_found(self):
        """Gets the incons_found of this ConsistencyCheckResponse.  # noqa: E501


        :return: The incons_found of this ConsistencyCheckResponse.  # noqa: E501
        :rtype: bool
        """
        return self._incons_found

    @incons_found.setter
    def incons_found(self, incons_found):
        """Sets the incons_found of this ConsistencyCheckResponse.


        :param incons_found: The incons_found of this ConsistencyCheckResponse.  # noqa: E501
        :type: bool
        """
        if incons_found is None:
            raise ValueError("Invalid value for `incons_found`, must not be `None`")  # noqa: E501

        self._incons_found = incons_found

    @property
    def status(self):
        """Gets the status of this ConsistencyCheckResponse.  # noqa: E501


        :return: The status of this ConsistencyCheckResponse.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ConsistencyCheckResponse.


        :param status: The status of this ConsistencyCheckResponse.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501
        allowed_values = ["IE_RUNNING", "IE_SUSPENDED", "IE_SOFTLY_SUSPENDED", "IE_ABORTED", "IE_SOFTLY_ABORTED", "IE_FINISHED"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConsistencyCheckResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConsistencyCheckResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
