# coding: utf-8

"""
    AristaFlowREST/OrgModelManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_org_model_manager
from af_org_model_manager.models.entity_initial_remote_iterator_data import EntityInitialRemoteIteratorData  # noqa: E501
from af_org_model_manager.rest import ApiException


class TestEntityInitialRemoteIteratorData(unittest.TestCase):
    """EntityInitialRemoteIteratorData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityInitialRemoteIteratorData(self):
        """Test EntityInitialRemoteIteratorData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_org_model_manager.models.entity_initial_remote_iterator_data.EntityInitialRemoteIteratorData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
