# coding: utf-8

"""
    AristaFlowREST/RuntimeService

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_runtime_service
from af_runtime_service.models.data_context import DataContext  # noqa: E501
from af_runtime_service.rest import ApiException


class TestDataContext(unittest.TestCase):
    """DataContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDataContext(self):
        """Test DataContext"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_runtime_service.models.data_context.DataContext()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
