# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


from . import _RTKPython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython
else:
    import _rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import itk.ITKCommonBasePython
import itk.pyBasePython
import itk.itkImageRTKPython
import itk.itkVectorPython
import itk.itkFixedArrayPython
import itk.vnl_vectorPython
import itk.stdcomplexPython
import itk.vnl_matrixPython
import itk.vnl_vector_refPython
import itk.itkIndexPython
import itk.itkOffsetPython
import itk.itkSizePython
import itk.itkCovariantVectorPython
import itk.itkImagePython
import itk.itkMatrixPython
import itk.itkPointPython
import itk.vnl_matrix_fixedPython
import itk.itkImageRegionPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkRGBPixelPython
import itk.itkRGBAPixelPython
import itk.itkImageBaseRTKPython
import itk.itkPointRTKPython
import itk.itkImageRegionRTKPython
import itk.itkMatrixRTKPython
import itk.itkCovariantVectorRTKPython
import itk.rtkFourDConjugateGradientConeBeamReconstructionFilterPython
import itk.itkArray2DPython
import itk.rtkBackProjectionImageFilterPython
import itk.itkInPlaceImageFilterAPython
import itk.itkImageToImageFilterAPython
import itk.itkImageToImageFilterCommonPython
import itk.itkVectorImagePython
import itk.itkVariableLengthVectorPython
import itk.itkImageSourcePython
import itk.itkImageSourceCommonPython
import itk.itkImageToImageFilterBPython
import itk.rtkThreeDCircularProjectionGeometryPython
import itk.rtkProjectionGeometryPython
import itk.itkImageToImageFilterRTKPython
import itk.itkImageSourceRTKPython
import itk.rtkForwardProjectionImageFilterPython
import itk.itkInPlaceImageFilterRTKPython

def rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3_New():
    return rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3.New()

class rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3(itk.rtkFourDConjugateGradientConeBeamReconstructionFilterPython.rtkFourDConjugateGradientConeBeamReconstructionFilterIF4IF3):
    r"""Proxy of C++ rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3___New_orig__)
    Clone = _swig_new_instance_method(_rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3_Clone)
    SetDisplacementField = _swig_new_instance_method(_rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3_SetDisplacementField)
    SetInverseDisplacementField = _swig_new_instance_method(_rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3_SetInverseDisplacementField)
    GetDisplacementField = _swig_new_instance_method(_rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3_GetDisplacementField)
    GetInverseDisplacementField = _swig_new_instance_method(_rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3_GetInverseDisplacementField)
    SetUseCudaCyclicDeformation = _swig_new_instance_method(_rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3_SetUseCudaCyclicDeformation)
    GetUseCudaCyclicDeformation = _swig_new_instance_method(_rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3_GetUseCudaCyclicDeformation)
    __swig_destroy__ = _rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.delete_rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3
    cast = _swig_new_static_method(_rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3_cast)

    def New(*args, **kargs):
        """New() -> rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3

        Create a new object of the class rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3 in _rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython:
_rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3_swigregister(rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3)
rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3___New_orig__ = _rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3___New_orig__
rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3_cast = _rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterPython.rtkMotionCompensatedFourDConjugateGradientConeBeamReconstructionFilterIF4IF3_cast


import itkHelpers
@itkHelpers.accept_numpy_array_like_xarray
def motion_compensated_four_d_conjugate_gradient_cone_beam_reconstruction_filter(*args, **kwargs):
    """Procedural interface for MotionCompensatedFourDConjugateGradientConeBeamReconstructionFilter"""
    import itk
    instance = itk.MotionCompensatedFourDConjugateGradientConeBeamReconstructionFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def motion_compensated_four_d_conjugate_gradient_cone_beam_reconstruction_filter_init_docstring():
    import itk
    import itkTemplate
    import itkHelpers
    if isinstance(itk.MotionCompensatedFourDConjugateGradientConeBeamReconstructionFilter, itkTemplate.itkTemplate):
        filter_object = itk.MotionCompensatedFourDConjugateGradientConeBeamReconstructionFilter.values()[0]
    else:
        filter_object = itk.MotionCompensatedFourDConjugateGradientConeBeamReconstructionFilter

    motion_compensated_four_d_conjugate_gradient_cone_beam_reconstruction_filter.__doc__ = filter_object.__doc__
    motion_compensated_four_d_conjugate_gradient_cone_beam_reconstruction_filter.__doc__ += "\n Args are Input(s) to the filter.\n"
    motion_compensated_four_d_conjugate_gradient_cone_beam_reconstruction_filter.__doc__ += "\n Available Keyword Arguments:\n"
    if isinstance(itk.MotionCompensatedFourDConjugateGradientConeBeamReconstructionFilter, itkTemplate.itkTemplate):
        motion_compensated_four_d_conjugate_gradient_cone_beam_reconstruction_filter.__doc__ += itkHelpers.filter_args(filter_object)[0]
        motion_compensated_four_d_conjugate_gradient_cone_beam_reconstruction_filter.__doc__ += "\n"
        motion_compensated_four_d_conjugate_gradient_cone_beam_reconstruction_filter.__doc__ += itkHelpers.filter_args(filter_object)[1]
    else:
        motion_compensated_four_d_conjugate_gradient_cone_beam_reconstruction_filter.__doc__ += "".join([
            "  " + itkHelpers.camel_to_snake_case(item[3:]) + "\n"
            for item in dir(filter_object)
            if item.startswith("Set")])



