# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


from . import _RTKPython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rtkLookupTableImageFilterPython
else:
    import _rtkLookupTableImageFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _rtkLookupTableImageFilterPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _rtkLookupTableImageFilterPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import itk.ITKCommonBasePython
import itk.pyBasePython
import itk.itkImageRegionPython
import itk.itkSizePython
import itk.itkIndexPython
import itk.itkOffsetPython
import itk.itkInPlaceImageFilterAPython
import itk.itkImageToImageFilterAPython
import itk.itkImageToImageFilterCommonPython
import itk.itkVectorImagePython
import itk.stdcomplexPython
import itk.itkVariableLengthVectorPython
import itk.itkImagePython
import itk.itkMatrixPython
import itk.itkVectorPython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.vnl_vector_refPython
import itk.itkFixedArrayPython
import itk.itkPointPython
import itk.vnl_matrix_fixedPython
import itk.itkCovariantVectorPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkRGBPixelPython
import itk.itkRGBAPixelPython
import itk.itkImageSourcePython
import itk.itkImageSourceCommonPython
import itk.itkImageToImageFilterBPython
import itk.itkImageRTKPython
import itk.itkImageBaseRTKPython
import itk.itkPointRTKPython
import itk.itkMatrixRTKPython
import itk.itkCovariantVectorRTKPython
import itk.itkImageRegionRTKPython
import itk.itkInPlaceImageFilterRTKPython
import itk.itkImageToImageFilterRTKPython
import itk.itkImageSourceRTKPython

def itkUnaryFunctorImageFilterIUI2ID2LUTUID_New():
    return itkUnaryFunctorImageFilterIUI2ID2LUTUID.New()

class itkUnaryFunctorImageFilterIUI2ID2LUTUID(itk.itkInPlaceImageFilterRTKPython.itkInPlaceImageFilterIUI2ID2):
    r"""Proxy of C++ itkUnaryFunctorImageFilterIUI2ID2LUTUID class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2ID2LUTUID___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2ID2LUTUID_Clone)
    GetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2ID2LUTUID_GetFunctor)
    SetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2ID2LUTUID_SetFunctor)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_itkUnaryFunctorImageFilterIUI2ID2LUTUID
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2ID2LUTUID_cast)

    def New(*args, **kargs):
        """New() -> itkUnaryFunctorImageFilterIUI2ID2LUTUID

        Create a new object of the class itkUnaryFunctorImageFilterIUI2ID2LUTUID and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkUnaryFunctorImageFilterIUI2ID2LUTUID.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkUnaryFunctorImageFilterIUI2ID2LUTUID.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkUnaryFunctorImageFilterIUI2ID2LUTUID.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkUnaryFunctorImageFilterIUI2ID2LUTUID in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2ID2LUTUID_swigregister(itkUnaryFunctorImageFilterIUI2ID2LUTUID)
itkUnaryFunctorImageFilterIUI2ID2LUTUID___New_orig__ = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2ID2LUTUID___New_orig__
itkUnaryFunctorImageFilterIUI2ID2LUTUID_cast = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2ID2LUTUID_cast


def itkUnaryFunctorImageFilterIUI2IF2LUTUIF_New():
    return itkUnaryFunctorImageFilterIUI2IF2LUTUIF.New()

class itkUnaryFunctorImageFilterIUI2IF2LUTUIF(itk.itkInPlaceImageFilterRTKPython.itkInPlaceImageFilterIUI2IF2):
    r"""Proxy of C++ itkUnaryFunctorImageFilterIUI2IF2LUTUIF class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2IF2LUTUIF___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2IF2LUTUIF_Clone)
    GetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2IF2LUTUIF_GetFunctor)
    SetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2IF2LUTUIF_SetFunctor)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_itkUnaryFunctorImageFilterIUI2IF2LUTUIF
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2IF2LUTUIF_cast)

    def New(*args, **kargs):
        """New() -> itkUnaryFunctorImageFilterIUI2IF2LUTUIF

        Create a new object of the class itkUnaryFunctorImageFilterIUI2IF2LUTUIF and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkUnaryFunctorImageFilterIUI2IF2LUTUIF.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkUnaryFunctorImageFilterIUI2IF2LUTUIF.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkUnaryFunctorImageFilterIUI2IF2LUTUIF.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkUnaryFunctorImageFilterIUI2IF2LUTUIF in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2IF2LUTUIF_swigregister(itkUnaryFunctorImageFilterIUI2IF2LUTUIF)
itkUnaryFunctorImageFilterIUI2IF2LUTUIF___New_orig__ = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2IF2LUTUIF___New_orig__
itkUnaryFunctorImageFilterIUI2IF2LUTUIF_cast = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI2IF2LUTUIF_cast


def itkUnaryFunctorImageFilterIUI3ID3LUTUID_New():
    return itkUnaryFunctorImageFilterIUI3ID3LUTUID.New()

class itkUnaryFunctorImageFilterIUI3ID3LUTUID(itk.itkInPlaceImageFilterRTKPython.itkInPlaceImageFilterIUI3ID3):
    r"""Proxy of C++ itkUnaryFunctorImageFilterIUI3ID3LUTUID class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3ID3LUTUID___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3ID3LUTUID_Clone)
    GetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3ID3LUTUID_GetFunctor)
    SetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3ID3LUTUID_SetFunctor)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_itkUnaryFunctorImageFilterIUI3ID3LUTUID
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3ID3LUTUID_cast)

    def New(*args, **kargs):
        """New() -> itkUnaryFunctorImageFilterIUI3ID3LUTUID

        Create a new object of the class itkUnaryFunctorImageFilterIUI3ID3LUTUID and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkUnaryFunctorImageFilterIUI3ID3LUTUID.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkUnaryFunctorImageFilterIUI3ID3LUTUID.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkUnaryFunctorImageFilterIUI3ID3LUTUID.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkUnaryFunctorImageFilterIUI3ID3LUTUID in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3ID3LUTUID_swigregister(itkUnaryFunctorImageFilterIUI3ID3LUTUID)
itkUnaryFunctorImageFilterIUI3ID3LUTUID___New_orig__ = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3ID3LUTUID___New_orig__
itkUnaryFunctorImageFilterIUI3ID3LUTUID_cast = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3ID3LUTUID_cast


def itkUnaryFunctorImageFilterIUI3IF3LUTUIF_New():
    return itkUnaryFunctorImageFilterIUI3IF3LUTUIF.New()

class itkUnaryFunctorImageFilterIUI3IF3LUTUIF(itk.itkInPlaceImageFilterRTKPython.itkInPlaceImageFilterIUI3IF3):
    r"""Proxy of C++ itkUnaryFunctorImageFilterIUI3IF3LUTUIF class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3IF3LUTUIF___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3IF3LUTUIF_Clone)
    GetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3IF3LUTUIF_GetFunctor)
    SetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3IF3LUTUIF_SetFunctor)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_itkUnaryFunctorImageFilterIUI3IF3LUTUIF
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3IF3LUTUIF_cast)

    def New(*args, **kargs):
        """New() -> itkUnaryFunctorImageFilterIUI3IF3LUTUIF

        Create a new object of the class itkUnaryFunctorImageFilterIUI3IF3LUTUIF and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkUnaryFunctorImageFilterIUI3IF3LUTUIF.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkUnaryFunctorImageFilterIUI3IF3LUTUIF.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkUnaryFunctorImageFilterIUI3IF3LUTUIF.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkUnaryFunctorImageFilterIUI3IF3LUTUIF in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3IF3LUTUIF_swigregister(itkUnaryFunctorImageFilterIUI3IF3LUTUIF)
itkUnaryFunctorImageFilterIUI3IF3LUTUIF___New_orig__ = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3IF3LUTUIF___New_orig__
itkUnaryFunctorImageFilterIUI3IF3LUTUIF_cast = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUI3IF3LUTUIF_cast


def itkUnaryFunctorImageFilterIUS2ID2LUTUSD_New():
    return itkUnaryFunctorImageFilterIUS2ID2LUTUSD.New()

class itkUnaryFunctorImageFilterIUS2ID2LUTUSD(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUS2ID2):
    r"""Proxy of C++ itkUnaryFunctorImageFilterIUS2ID2LUTUSD class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2ID2LUTUSD___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2ID2LUTUSD_Clone)
    GetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2ID2LUTUSD_GetFunctor)
    SetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2ID2LUTUSD_SetFunctor)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_itkUnaryFunctorImageFilterIUS2ID2LUTUSD
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2ID2LUTUSD_cast)

    def New(*args, **kargs):
        """New() -> itkUnaryFunctorImageFilterIUS2ID2LUTUSD

        Create a new object of the class itkUnaryFunctorImageFilterIUS2ID2LUTUSD and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkUnaryFunctorImageFilterIUS2ID2LUTUSD.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkUnaryFunctorImageFilterIUS2ID2LUTUSD.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkUnaryFunctorImageFilterIUS2ID2LUTUSD.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkUnaryFunctorImageFilterIUS2ID2LUTUSD in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2ID2LUTUSD_swigregister(itkUnaryFunctorImageFilterIUS2ID2LUTUSD)
itkUnaryFunctorImageFilterIUS2ID2LUTUSD___New_orig__ = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2ID2LUTUSD___New_orig__
itkUnaryFunctorImageFilterIUS2ID2LUTUSD_cast = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2ID2LUTUSD_cast


def itkUnaryFunctorImageFilterIUS2IF2LUTUSF_New():
    return itkUnaryFunctorImageFilterIUS2IF2LUTUSF.New()

class itkUnaryFunctorImageFilterIUS2IF2LUTUSF(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUS2IF2):
    r"""Proxy of C++ itkUnaryFunctorImageFilterIUS2IF2LUTUSF class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IF2LUTUSF___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IF2LUTUSF_Clone)
    GetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IF2LUTUSF_GetFunctor)
    SetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IF2LUTUSF_SetFunctor)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_itkUnaryFunctorImageFilterIUS2IF2LUTUSF
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IF2LUTUSF_cast)

    def New(*args, **kargs):
        """New() -> itkUnaryFunctorImageFilterIUS2IF2LUTUSF

        Create a new object of the class itkUnaryFunctorImageFilterIUS2IF2LUTUSF and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkUnaryFunctorImageFilterIUS2IF2LUTUSF.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkUnaryFunctorImageFilterIUS2IF2LUTUSF.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkUnaryFunctorImageFilterIUS2IF2LUTUSF.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkUnaryFunctorImageFilterIUS2IF2LUTUSF in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IF2LUTUSF_swigregister(itkUnaryFunctorImageFilterIUS2IF2LUTUSF)
itkUnaryFunctorImageFilterIUS2IF2LUTUSF___New_orig__ = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IF2LUTUSF___New_orig__
itkUnaryFunctorImageFilterIUS2IF2LUTUSF_cast = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IF2LUTUSF_cast


def itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS_New():
    return itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS.New()

class itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUS2IUS2):
    r"""Proxy of C++ itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS_Clone)
    GetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS_GetFunctor)
    SetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS_SetFunctor)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS_cast)

    def New(*args, **kargs):
        """New() -> itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS

        Create a new object of the class itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS_swigregister(itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS)
itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS___New_orig__ = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS___New_orig__
itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS_cast = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS_cast


def itkUnaryFunctorImageFilterIUS3ID3LUTUSD_New():
    return itkUnaryFunctorImageFilterIUS3ID3LUTUSD.New()

class itkUnaryFunctorImageFilterIUS3ID3LUTUSD(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUS3ID3):
    r"""Proxy of C++ itkUnaryFunctorImageFilterIUS3ID3LUTUSD class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3ID3LUTUSD___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3ID3LUTUSD_Clone)
    GetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3ID3LUTUSD_GetFunctor)
    SetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3ID3LUTUSD_SetFunctor)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_itkUnaryFunctorImageFilterIUS3ID3LUTUSD
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3ID3LUTUSD_cast)

    def New(*args, **kargs):
        """New() -> itkUnaryFunctorImageFilterIUS3ID3LUTUSD

        Create a new object of the class itkUnaryFunctorImageFilterIUS3ID3LUTUSD and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkUnaryFunctorImageFilterIUS3ID3LUTUSD.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkUnaryFunctorImageFilterIUS3ID3LUTUSD.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkUnaryFunctorImageFilterIUS3ID3LUTUSD.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkUnaryFunctorImageFilterIUS3ID3LUTUSD in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3ID3LUTUSD_swigregister(itkUnaryFunctorImageFilterIUS3ID3LUTUSD)
itkUnaryFunctorImageFilterIUS3ID3LUTUSD___New_orig__ = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3ID3LUTUSD___New_orig__
itkUnaryFunctorImageFilterIUS3ID3LUTUSD_cast = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3ID3LUTUSD_cast


def itkUnaryFunctorImageFilterIUS3IF3LUTUSF_New():
    return itkUnaryFunctorImageFilterIUS3IF3LUTUSF.New()

class itkUnaryFunctorImageFilterIUS3IF3LUTUSF(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUS3IF3):
    r"""Proxy of C++ itkUnaryFunctorImageFilterIUS3IF3LUTUSF class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IF3LUTUSF___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IF3LUTUSF_Clone)
    GetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IF3LUTUSF_GetFunctor)
    SetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IF3LUTUSF_SetFunctor)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_itkUnaryFunctorImageFilterIUS3IF3LUTUSF
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IF3LUTUSF_cast)

    def New(*args, **kargs):
        """New() -> itkUnaryFunctorImageFilterIUS3IF3LUTUSF

        Create a new object of the class itkUnaryFunctorImageFilterIUS3IF3LUTUSF and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkUnaryFunctorImageFilterIUS3IF3LUTUSF.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkUnaryFunctorImageFilterIUS3IF3LUTUSF.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkUnaryFunctorImageFilterIUS3IF3LUTUSF.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkUnaryFunctorImageFilterIUS3IF3LUTUSF in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IF3LUTUSF_swigregister(itkUnaryFunctorImageFilterIUS3IF3LUTUSF)
itkUnaryFunctorImageFilterIUS3IF3LUTUSF___New_orig__ = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IF3LUTUSF___New_orig__
itkUnaryFunctorImageFilterIUS3IF3LUTUSF_cast = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IF3LUTUSF_cast


def itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS_New():
    return itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS.New()

class itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIUS3IUS3):
    r"""Proxy of C++ itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS_Clone)
    GetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS_GetFunctor)
    SetFunctor = _swig_new_instance_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS_SetFunctor)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS_cast)

    def New(*args, **kargs):
        """New() -> itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS

        Create a new object of the class itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS_swigregister(itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS)
itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS___New_orig__ = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS___New_orig__
itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS_cast = _rtkLookupTableImageFilterPython.itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS_cast

class rtkFunctorLUTUID(object):
    r"""Proxy of C++ rtkFunctorLUTUID class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkFunctorLUTUID
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUID_SetLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUID_GetLookupTable)
    __ne__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUID___ne__)
    __eq__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUID___eq__)
    __call__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUID___call__)

    def __init__(self, *args):
        r"""
        __init__(rtkFunctorLUTUID self) -> rtkFunctorLUTUID
        __init__(rtkFunctorLUTUID self, rtkFunctorLUTUID arg0) -> rtkFunctorLUTUID
        """
        _rtkLookupTableImageFilterPython.rtkFunctorLUTUID_swiginit(self, _rtkLookupTableImageFilterPython.new_rtkFunctorLUTUID(*args))

# Register rtkFunctorLUTUID in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkFunctorLUTUID_swigregister(rtkFunctorLUTUID)

class rtkFunctorLUTUIF(object):
    r"""Proxy of C++ rtkFunctorLUTUIF class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkFunctorLUTUIF
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUIF_SetLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUIF_GetLookupTable)
    __ne__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUIF___ne__)
    __eq__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUIF___eq__)
    __call__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUIF___call__)

    def __init__(self, *args):
        r"""
        __init__(rtkFunctorLUTUIF self) -> rtkFunctorLUTUIF
        __init__(rtkFunctorLUTUIF self, rtkFunctorLUTUIF arg0) -> rtkFunctorLUTUIF
        """
        _rtkLookupTableImageFilterPython.rtkFunctorLUTUIF_swiginit(self, _rtkLookupTableImageFilterPython.new_rtkFunctorLUTUIF(*args))

# Register rtkFunctorLUTUIF in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkFunctorLUTUIF_swigregister(rtkFunctorLUTUIF)

class rtkFunctorLUTUSD(object):
    r"""Proxy of C++ rtkFunctorLUTUSD class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkFunctorLUTUSD
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSD_SetLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSD_GetLookupTable)
    __ne__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSD___ne__)
    __eq__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSD___eq__)
    __call__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSD___call__)

    def __init__(self, *args):
        r"""
        __init__(rtkFunctorLUTUSD self) -> rtkFunctorLUTUSD
        __init__(rtkFunctorLUTUSD self, rtkFunctorLUTUSD arg0) -> rtkFunctorLUTUSD
        """
        _rtkLookupTableImageFilterPython.rtkFunctorLUTUSD_swiginit(self, _rtkLookupTableImageFilterPython.new_rtkFunctorLUTUSD(*args))

# Register rtkFunctorLUTUSD in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkFunctorLUTUSD_swigregister(rtkFunctorLUTUSD)

class rtkFunctorLUTUSF(object):
    r"""Proxy of C++ rtkFunctorLUTUSF class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkFunctorLUTUSF
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSF_SetLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSF_GetLookupTable)
    __ne__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSF___ne__)
    __eq__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSF___eq__)
    __call__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSF___call__)

    def __init__(self, *args):
        r"""
        __init__(rtkFunctorLUTUSF self) -> rtkFunctorLUTUSF
        __init__(rtkFunctorLUTUSF self, rtkFunctorLUTUSF arg0) -> rtkFunctorLUTUSF
        """
        _rtkLookupTableImageFilterPython.rtkFunctorLUTUSF_swiginit(self, _rtkLookupTableImageFilterPython.new_rtkFunctorLUTUSF(*args))

# Register rtkFunctorLUTUSF in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkFunctorLUTUSF_swigregister(rtkFunctorLUTUSF)

class rtkFunctorLUTUSUS(object):
    r"""Proxy of C++ rtkFunctorLUTUSUS class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkFunctorLUTUSUS
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSUS_SetLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSUS_GetLookupTable)
    __ne__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSUS___ne__)
    __eq__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSUS___eq__)
    __call__ = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkFunctorLUTUSUS___call__)

    def __init__(self, *args):
        r"""
        __init__(rtkFunctorLUTUSUS self) -> rtkFunctorLUTUSUS
        __init__(rtkFunctorLUTUSUS self, rtkFunctorLUTUSUS arg0) -> rtkFunctorLUTUSUS
        """
        _rtkLookupTableImageFilterPython.rtkFunctorLUTUSUS_swiginit(self, _rtkLookupTableImageFilterPython.new_rtkFunctorLUTUSUS(*args))

# Register rtkFunctorLUTUSUS in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkFunctorLUTUSUS_swigregister(rtkFunctorLUTUSUS)


def rtkLookupTableImageFilterIUI2ID2_New():
    return rtkLookupTableImageFilterIUI2ID2.New()

class rtkLookupTableImageFilterIUI2ID2(itkUnaryFunctorImageFilterIUI2ID2LUTUID):
    r"""Proxy of C++ rtkLookupTableImageFilterIUI2ID2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2ID2___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2ID2_Clone)
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2ID2_SetLookupTable)
    GetModifiableLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2ID2_GetModifiableLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2ID2_GetLookupTable)
    BeforeThreadedGenerateData = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2ID2_BeforeThreadedGenerateData)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkLookupTableImageFilterIUI2ID2
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2ID2_cast)

    def New(*args, **kargs):
        """New() -> rtkLookupTableImageFilterIUI2ID2

        Create a new object of the class rtkLookupTableImageFilterIUI2ID2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkLookupTableImageFilterIUI2ID2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkLookupTableImageFilterIUI2ID2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkLookupTableImageFilterIUI2ID2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkLookupTableImageFilterIUI2ID2 in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2ID2_swigregister(rtkLookupTableImageFilterIUI2ID2)
rtkLookupTableImageFilterIUI2ID2___New_orig__ = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2ID2___New_orig__
rtkLookupTableImageFilterIUI2ID2_cast = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2ID2_cast


def rtkLookupTableImageFilterIUI2IF2_New():
    return rtkLookupTableImageFilterIUI2IF2.New()

class rtkLookupTableImageFilterIUI2IF2(itkUnaryFunctorImageFilterIUI2IF2LUTUIF):
    r"""Proxy of C++ rtkLookupTableImageFilterIUI2IF2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2IF2___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2IF2_Clone)
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2IF2_SetLookupTable)
    GetModifiableLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2IF2_GetModifiableLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2IF2_GetLookupTable)
    BeforeThreadedGenerateData = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2IF2_BeforeThreadedGenerateData)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkLookupTableImageFilterIUI2IF2
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2IF2_cast)

    def New(*args, **kargs):
        """New() -> rtkLookupTableImageFilterIUI2IF2

        Create a new object of the class rtkLookupTableImageFilterIUI2IF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkLookupTableImageFilterIUI2IF2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkLookupTableImageFilterIUI2IF2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkLookupTableImageFilterIUI2IF2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkLookupTableImageFilterIUI2IF2 in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2IF2_swigregister(rtkLookupTableImageFilterIUI2IF2)
rtkLookupTableImageFilterIUI2IF2___New_orig__ = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2IF2___New_orig__
rtkLookupTableImageFilterIUI2IF2_cast = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI2IF2_cast


def rtkLookupTableImageFilterIUI3ID3_New():
    return rtkLookupTableImageFilterIUI3ID3.New()

class rtkLookupTableImageFilterIUI3ID3(itkUnaryFunctorImageFilterIUI3ID3LUTUID):
    r"""Proxy of C++ rtkLookupTableImageFilterIUI3ID3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3ID3___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3ID3_Clone)
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3ID3_SetLookupTable)
    GetModifiableLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3ID3_GetModifiableLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3ID3_GetLookupTable)
    BeforeThreadedGenerateData = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3ID3_BeforeThreadedGenerateData)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkLookupTableImageFilterIUI3ID3
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3ID3_cast)

    def New(*args, **kargs):
        """New() -> rtkLookupTableImageFilterIUI3ID3

        Create a new object of the class rtkLookupTableImageFilterIUI3ID3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkLookupTableImageFilterIUI3ID3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkLookupTableImageFilterIUI3ID3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkLookupTableImageFilterIUI3ID3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkLookupTableImageFilterIUI3ID3 in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3ID3_swigregister(rtkLookupTableImageFilterIUI3ID3)
rtkLookupTableImageFilterIUI3ID3___New_orig__ = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3ID3___New_orig__
rtkLookupTableImageFilterIUI3ID3_cast = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3ID3_cast


def rtkLookupTableImageFilterIUI3IF3_New():
    return rtkLookupTableImageFilterIUI3IF3.New()

class rtkLookupTableImageFilterIUI3IF3(itkUnaryFunctorImageFilterIUI3IF3LUTUIF):
    r"""Proxy of C++ rtkLookupTableImageFilterIUI3IF3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3IF3___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3IF3_Clone)
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3IF3_SetLookupTable)
    GetModifiableLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3IF3_GetModifiableLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3IF3_GetLookupTable)
    BeforeThreadedGenerateData = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3IF3_BeforeThreadedGenerateData)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkLookupTableImageFilterIUI3IF3
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3IF3_cast)

    def New(*args, **kargs):
        """New() -> rtkLookupTableImageFilterIUI3IF3

        Create a new object of the class rtkLookupTableImageFilterIUI3IF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkLookupTableImageFilterIUI3IF3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkLookupTableImageFilterIUI3IF3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkLookupTableImageFilterIUI3IF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkLookupTableImageFilterIUI3IF3 in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3IF3_swigregister(rtkLookupTableImageFilterIUI3IF3)
rtkLookupTableImageFilterIUI3IF3___New_orig__ = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3IF3___New_orig__
rtkLookupTableImageFilterIUI3IF3_cast = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUI3IF3_cast


def rtkLookupTableImageFilterIUS2ID2_New():
    return rtkLookupTableImageFilterIUS2ID2.New()

class rtkLookupTableImageFilterIUS2ID2(itkUnaryFunctorImageFilterIUS2ID2LUTUSD):
    r"""Proxy of C++ rtkLookupTableImageFilterIUS2ID2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2ID2___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2ID2_Clone)
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2ID2_SetLookupTable)
    GetModifiableLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2ID2_GetModifiableLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2ID2_GetLookupTable)
    BeforeThreadedGenerateData = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2ID2_BeforeThreadedGenerateData)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkLookupTableImageFilterIUS2ID2
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2ID2_cast)

    def New(*args, **kargs):
        """New() -> rtkLookupTableImageFilterIUS2ID2

        Create a new object of the class rtkLookupTableImageFilterIUS2ID2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkLookupTableImageFilterIUS2ID2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkLookupTableImageFilterIUS2ID2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkLookupTableImageFilterIUS2ID2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkLookupTableImageFilterIUS2ID2 in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2ID2_swigregister(rtkLookupTableImageFilterIUS2ID2)
rtkLookupTableImageFilterIUS2ID2___New_orig__ = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2ID2___New_orig__
rtkLookupTableImageFilterIUS2ID2_cast = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2ID2_cast


def rtkLookupTableImageFilterIUS2IF2_New():
    return rtkLookupTableImageFilterIUS2IF2.New()

class rtkLookupTableImageFilterIUS2IF2(itkUnaryFunctorImageFilterIUS2IF2LUTUSF):
    r"""Proxy of C++ rtkLookupTableImageFilterIUS2IF2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IF2___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IF2_Clone)
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IF2_SetLookupTable)
    GetModifiableLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IF2_GetModifiableLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IF2_GetLookupTable)
    BeforeThreadedGenerateData = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IF2_BeforeThreadedGenerateData)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkLookupTableImageFilterIUS2IF2
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IF2_cast)

    def New(*args, **kargs):
        """New() -> rtkLookupTableImageFilterIUS2IF2

        Create a new object of the class rtkLookupTableImageFilterIUS2IF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkLookupTableImageFilterIUS2IF2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkLookupTableImageFilterIUS2IF2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkLookupTableImageFilterIUS2IF2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkLookupTableImageFilterIUS2IF2 in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IF2_swigregister(rtkLookupTableImageFilterIUS2IF2)
rtkLookupTableImageFilterIUS2IF2___New_orig__ = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IF2___New_orig__
rtkLookupTableImageFilterIUS2IF2_cast = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IF2_cast


def rtkLookupTableImageFilterIUS2IUS2_New():
    return rtkLookupTableImageFilterIUS2IUS2.New()

class rtkLookupTableImageFilterIUS2IUS2(itkUnaryFunctorImageFilterIUS2IUS2LUTUSUS):
    r"""Proxy of C++ rtkLookupTableImageFilterIUS2IUS2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IUS2___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IUS2_Clone)
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IUS2_SetLookupTable)
    GetModifiableLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IUS2_GetModifiableLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IUS2_GetLookupTable)
    BeforeThreadedGenerateData = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IUS2_BeforeThreadedGenerateData)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkLookupTableImageFilterIUS2IUS2
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IUS2_cast)

    def New(*args, **kargs):
        """New() -> rtkLookupTableImageFilterIUS2IUS2

        Create a new object of the class rtkLookupTableImageFilterIUS2IUS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkLookupTableImageFilterIUS2IUS2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkLookupTableImageFilterIUS2IUS2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkLookupTableImageFilterIUS2IUS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkLookupTableImageFilterIUS2IUS2 in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IUS2_swigregister(rtkLookupTableImageFilterIUS2IUS2)
rtkLookupTableImageFilterIUS2IUS2___New_orig__ = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IUS2___New_orig__
rtkLookupTableImageFilterIUS2IUS2_cast = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IUS2_cast


def rtkLookupTableImageFilterIUS3ID3_New():
    return rtkLookupTableImageFilterIUS3ID3.New()

class rtkLookupTableImageFilterIUS3ID3(itkUnaryFunctorImageFilterIUS3ID3LUTUSD):
    r"""Proxy of C++ rtkLookupTableImageFilterIUS3ID3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3ID3___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3ID3_Clone)
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3ID3_SetLookupTable)
    GetModifiableLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3ID3_GetModifiableLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3ID3_GetLookupTable)
    BeforeThreadedGenerateData = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3ID3_BeforeThreadedGenerateData)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkLookupTableImageFilterIUS3ID3
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3ID3_cast)

    def New(*args, **kargs):
        """New() -> rtkLookupTableImageFilterIUS3ID3

        Create a new object of the class rtkLookupTableImageFilterIUS3ID3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkLookupTableImageFilterIUS3ID3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkLookupTableImageFilterIUS3ID3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkLookupTableImageFilterIUS3ID3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkLookupTableImageFilterIUS3ID3 in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3ID3_swigregister(rtkLookupTableImageFilterIUS3ID3)
rtkLookupTableImageFilterIUS3ID3___New_orig__ = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3ID3___New_orig__
rtkLookupTableImageFilterIUS3ID3_cast = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3ID3_cast


def rtkLookupTableImageFilterIUS3IF3_New():
    return rtkLookupTableImageFilterIUS3IF3.New()

class rtkLookupTableImageFilterIUS3IF3(itkUnaryFunctorImageFilterIUS3IF3LUTUSF):
    r"""Proxy of C++ rtkLookupTableImageFilterIUS3IF3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IF3___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IF3_Clone)
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IF3_SetLookupTable)
    GetModifiableLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IF3_GetModifiableLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IF3_GetLookupTable)
    BeforeThreadedGenerateData = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IF3_BeforeThreadedGenerateData)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkLookupTableImageFilterIUS3IF3
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IF3_cast)

    def New(*args, **kargs):
        """New() -> rtkLookupTableImageFilterIUS3IF3

        Create a new object of the class rtkLookupTableImageFilterIUS3IF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkLookupTableImageFilterIUS3IF3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkLookupTableImageFilterIUS3IF3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkLookupTableImageFilterIUS3IF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkLookupTableImageFilterIUS3IF3 in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IF3_swigregister(rtkLookupTableImageFilterIUS3IF3)
rtkLookupTableImageFilterIUS3IF3___New_orig__ = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IF3___New_orig__
rtkLookupTableImageFilterIUS3IF3_cast = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IF3_cast


def rtkLookupTableImageFilterIUS3IUS3_New():
    return rtkLookupTableImageFilterIUS3IUS3.New()

class rtkLookupTableImageFilterIUS3IUS3(itkUnaryFunctorImageFilterIUS3IUS3LUTUSUS):
    r"""Proxy of C++ rtkLookupTableImageFilterIUS3IUS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IUS3___New_orig__)
    Clone = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IUS3_Clone)
    SetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IUS3_SetLookupTable)
    GetModifiableLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IUS3_GetModifiableLookupTable)
    GetLookupTable = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IUS3_GetLookupTable)
    BeforeThreadedGenerateData = _swig_new_instance_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IUS3_BeforeThreadedGenerateData)
    __swig_destroy__ = _rtkLookupTableImageFilterPython.delete_rtkLookupTableImageFilterIUS3IUS3
    cast = _swig_new_static_method(_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IUS3_cast)

    def New(*args, **kargs):
        """New() -> rtkLookupTableImageFilterIUS3IUS3

        Create a new object of the class rtkLookupTableImageFilterIUS3IUS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkLookupTableImageFilterIUS3IUS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkLookupTableImageFilterIUS3IUS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkLookupTableImageFilterIUS3IUS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkLookupTableImageFilterIUS3IUS3 in _rtkLookupTableImageFilterPython:
_rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IUS3_swigregister(rtkLookupTableImageFilterIUS3IUS3)
rtkLookupTableImageFilterIUS3IUS3___New_orig__ = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IUS3___New_orig__
rtkLookupTableImageFilterIUS3IUS3_cast = _rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IUS3_cast


import itkHelpers
@itkHelpers.accept_numpy_array_like_xarray
def lookup_table_image_filter(*args, **kwargs):
    """Procedural interface for LookupTableImageFilter"""
    import itk
    instance = itk.LookupTableImageFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def lookup_table_image_filter_init_docstring():
    import itk
    import itkTemplate
    import itkHelpers
    if isinstance(itk.LookupTableImageFilter, itkTemplate.itkTemplate):
        filter_object = itk.LookupTableImageFilter.values()[0]
    else:
        filter_object = itk.LookupTableImageFilter

    lookup_table_image_filter.__doc__ = filter_object.__doc__
    lookup_table_image_filter.__doc__ += "\n Args are Input(s) to the filter.\n"
    lookup_table_image_filter.__doc__ += "\n Available Keyword Arguments:\n"
    if isinstance(itk.LookupTableImageFilter, itkTemplate.itkTemplate):
        lookup_table_image_filter.__doc__ += itkHelpers.filter_args(filter_object)[0]
        lookup_table_image_filter.__doc__ += "\n"
        lookup_table_image_filter.__doc__ += itkHelpers.filter_args(filter_object)[1]
    else:
        lookup_table_image_filter.__doc__ += "".join([
            "  " + itkHelpers.camel_to_snake_case(item[3:]) + "\n"
            for item in dir(filter_object)
            if item.startswith("Set")])
import itkHelpers
@itkHelpers.accept_numpy_array_like_xarray
def unary_functor_image_filter(*args, **kwargs):
    """Procedural interface for UnaryFunctorImageFilter"""
    import itk
    instance = itk.UnaryFunctorImageFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def unary_functor_image_filter_init_docstring():
    import itk
    import itkTemplate
    import itkHelpers
    if isinstance(itk.UnaryFunctorImageFilter, itkTemplate.itkTemplate):
        filter_object = itk.UnaryFunctorImageFilter.values()[0]
    else:
        filter_object = itk.UnaryFunctorImageFilter

    unary_functor_image_filter.__doc__ = filter_object.__doc__
    unary_functor_image_filter.__doc__ += "\n Args are Input(s) to the filter.\n"
    unary_functor_image_filter.__doc__ += "\n Available Keyword Arguments:\n"
    if isinstance(itk.UnaryFunctorImageFilter, itkTemplate.itkTemplate):
        unary_functor_image_filter.__doc__ += itkHelpers.filter_args(filter_object)[0]
        unary_functor_image_filter.__doc__ += "\n"
        unary_functor_image_filter.__doc__ += itkHelpers.filter_args(filter_object)[1]
    else:
        unary_functor_image_filter.__doc__ += "".join([
            "  " + itkHelpers.camel_to_snake_case(item[3:]) + "\n"
            for item in dir(filter_object)
            if item.startswith("Set")])



