# coding: utf-8

"""
    Oliver API

    Oliver web API service  # noqa: E501

    OpenAPI spec version: 4.1.0
    Contact: api@behavioralsignals.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import behavioral_signals_swagger_client
from behavioral_signals_swagger_client.models.agent import Agent  # noqa: E501
from behavioral_signals_swagger_client.rest import ApiException


class TestAgent(unittest.TestCase):
    """Agent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgent(self):
        """Test Agent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = behavioral_signals_swagger_client.models.agent.Agent()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
