# coding: utf-8

"""
    AristaFlowREST/ExecutionManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_execution_manager
from af_execution_manager.models.enquiry import Enquiry  # noqa: E501
from af_execution_manager.rest import ApiException


class TestEnquiry(unittest.TestCase):
    """Enquiry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnquiry(self):
        """Test Enquiry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_execution_manager.models.enquiry.Enquiry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
