# coding: utf-8

"""
    AristaFlowREST/ExecutionManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_execution_manager
from af_execution_manager.api.qa_remote_iterator_api import QaRemoteIteratorApi  # noqa: E501
from af_execution_manager.rest import ApiException


class TestQaRemoteIteratorApi(unittest.TestCase):
    """QaRemoteIteratorApi unit test stubs"""

    def setUp(self):
        self.api = QaRemoteIteratorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_drop(self):
        """Test case for drop

        """
        pass

    def test_get_next(self):
        """Test case for get_next

        """
        pass

    def test_get_previous(self):
        """Test case for get_previous

        """
        pass

    def test_keep_alive(self):
        """Test case for keep_alive

        """
        pass


if __name__ == '__main__':
    unittest.main()
