# coding: utf-8

"""
    AristaFlowREST/ExecutionManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_execution_manager
from af_execution_manager.models.inline_response4006 import InlineResponse4006  # noqa: E501
from af_execution_manager.rest import ApiException


class TestInlineResponse4006(unittest.TestCase):
    """InlineResponse4006 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse4006(self):
        """Test InlineResponse4006"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_execution_manager.models.inline_response4006.InlineResponse4006()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
