# coding: utf-8

"""
    AristaFlowREST/RuntimeService

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_runtime_service
from af_runtime_service.models.one_ofinline_response500 import OneOfinlineResponse500  # noqa: E501
from af_runtime_service.rest import ApiException


class TestOneOfinlineResponse500(unittest.TestCase):
    """OneOfinlineResponse500 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfinlineResponse500(self):
        """Test OneOfinlineResponse500"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_runtime_service.models.one_ofinline_response500.OneOfinlineResponse500()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
