
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/mcot/utils:dist

from setuptools import setup

setup(**{
    'author': 'Michiel Cottaar',
    'author_email': 'Michiel.Cottaar@ndcn.ox.ac.uk',
    'classifiers': [
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Operating System :: OS Independent',
    ],
    'description': 'Utilities for mcot including script interface',
    'license': 'MIT license',
    'long_description': """Script interface for all mcot submodules

Defines the mcot command line tool""",
    'name': 'mcot.utils',
    'python_requires': '>=3.6',
    'url': 'https://git.fmrib.ox.ac.uk/ndcn0236/mcot',
    'version': '0.1.0',
    'package_dir': {
        '': 'src',
    },
    'packages': (
        'mcot',
        'mcot.utils',
        'mcot.utils._scripts',
        'mcot.utils._scripts.split',
        'mcot.utils._scripts.tree',
    ),
    'namespace_packages': (
    ),
    'package_data': {
        'mcot.utils': (
            'README.rst',
            'VERSION',
        ),
    },
    'install_requires': (
        'fslpy',
        'loguru',
        'mcot.surface~=0.1.0',
        'nibabel',
        'numpy',
        'pandas',
    ),
    'entry_points': {
        'console_scripts': [
            'mcot=mcot.utils.scripts:run',
        ],
    },
})
