# coding: utf-8

"""
    AristaFlowREST/ProcessManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_process_manager
from af_process_manager.models.script_environment_exception import ScriptEnvironmentException  # noqa: E501
from af_process_manager.rest import ApiException


class TestScriptEnvironmentException(unittest.TestCase):
    """ScriptEnvironmentException unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScriptEnvironmentException(self):
        """Test ScriptEnvironmentException"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_process_manager.models.script_environment_exception.ScriptEnvironmentException()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
