#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['yaqc_bluesky']

package_data = \
{'': ['*']}

install_requires = \
['yaqc>=2020.7.3', 'bluesky>=1.6.6', 'happi>=1.8.4']

extras_require = \
{'dev': ['black', 'pre-commit', 'pytest', 'yaqd_core', 'yaqd_fakes', 'mypy']}

entry_points = \
{'happi.containers': ['yaq = yaqc_bluesky._happi']}

setup(name='yaqc-bluesky',
      version='2021.1.1',
      description='A bluesky interface to the yaq instrument control framework.',
      author='Blaise Thompson',
      author_email='blaise@untzag.com',
      url='https://github.com/bluesky/yaqc-bluesky',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>3.7',
     )
