from typing import Any

def main() -> None: ...
def state(file: str, start: str, end: str, output_file: str, engine: str) -> Any: ...
def string(file: str, start: str, end: str, output: str, string: str, engine: str) -> Any: ...
