
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-20T16:20:59-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "73877a62da14c90eade6695ac94778adae2171db",
 "version": "1.16.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
