# coding: utf-8

"""
    AristaFlowREST/OrgModelManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_org_model_manager
from af_org_model_manager.api.client_administration_api import ClientAdministrationApi  # noqa: E501
from af_org_model_manager.rest import ApiException


class TestClientAdministrationApi(unittest.TestCase):
    """ClientAdministrationApi unit test stubs"""

    def setUp(self):
        self.api = ClientAdministrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_change_mail_address(self):
        """Test case for change_mail_address

        """
        pass

    def test_change_password(self):
        """Test case for change_password

        """
        pass

    def test_change_preferred_locale(self):
        """Test case for change_preferred_locale

        """
        pass

    def test_get_mail_address(self):
        """Test case for get_mail_address

        """
        pass

    def test_get_preferred_locale(self):
        """Test case for get_preferred_locale

        """
        pass


if __name__ == '__main__':
    unittest.main()
