# coding: utf-8

"""
    AristaFlowREST/ExecutionManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_execution_manager
from af_execution_manager.models.inst_id_pair_remote_iterator_data import InstIdPairRemoteIteratorData  # noqa: E501
from af_execution_manager.rest import ApiException


class TestInstIdPairRemoteIteratorData(unittest.TestCase):
    """InstIdPairRemoteIteratorData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstIdPairRemoteIteratorData(self):
        """Test InstIdPairRemoteIteratorData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_execution_manager.models.inst_id_pair_remote_iterator_data.InstIdPairRemoteIteratorData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
