# Generated by Django 3.0.4 on 2020-12-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenmailbox', '0007_auto_20201229_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
    ]
