
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-19T17:10:12-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0678528cc5be6f2c1f531afea1949ee5fa926c6",
 "version": "v1.1.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
