
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-21T23:55:20+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a590aa93acb8d0efbe531892ca976f741b226ee4",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
