# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


from . import _RTKPython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rtkSimplexSpectralProjectionsDecompositionImageFilterPython
else:
    import _rtkSimplexSpectralProjectionsDecompositionImageFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import itk.itkVectorImagePython
import itk.itkImagePython
import itk.itkRGBPixelPython
import itk.itkFixedArrayPython
import itk.pyBasePython
import itk.itkPointPython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.stdcomplexPython
import itk.vnl_vector_refPython
import itk.itkVectorPython
import itk.itkMatrixPython
import itk.itkCovariantVectorPython
import itk.vnl_matrix_fixedPython
import itk.itkSizePython
import itk.itkOffsetPython
import itk.itkImageRegionPython
import itk.itkIndexPython
import itk.ITKCommonBasePython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkRGBAPixelPython
import itk.itkVariableLengthVectorPython
import itk.itkImageRTKPython
import itk.itkImageBaseRTKPython
import itk.itkImageRegionRTKPython
import itk.itkPointRTKPython
import itk.itkMatrixRTKPython
import itk.itkCovariantVectorRTKPython
import itk.itkVectorImageRTKPython
import itk.itkImageToImageFilterAPython
import itk.itkImageSourcePython
import itk.itkImageSourceCommonPython
import itk.itkImageToImageFilterCommonPython

def rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_New():
    return rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2.New()

class rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterVID3VID3):
    r"""Proxy of C++ rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2___New_orig__)
    Clone = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_Clone)
    SetInputDecomposedProjections = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetInputDecomposedProjections)
    GetInputDecomposedProjections = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetInputDecomposedProjections)
    SetInputMeasuredProjections = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetInputMeasuredProjections)
    GetInputMeasuredProjections = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetInputMeasuredProjections)
    SetDetectorResponse = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetDetectorResponse)
    GetDetectorResponse = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetDetectorResponse)
    SetMaterialAttenuations = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetMaterialAttenuations)
    GetMaterialAttenuations = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetMaterialAttenuations)
    SetInputIncidentSpectrum = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetInputIncidentSpectrum)
    SetInputSecondIncidentSpectrum = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetInputSecondIncidentSpectrum)
    GetInputIncidentSpectrum = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetInputIncidentSpectrum)
    GetInputSecondIncidentSpectrum = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetInputSecondIncidentSpectrum)
    GetNumberOfIterations = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetNumberOfIterations)
    SetNumberOfIterations = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetNumberOfIterations)
    SetNumberOfEnergies = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetNumberOfEnergies)
    GetNumberOfEnergies = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetNumberOfEnergies)
    SetNumberOfMaterials = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetNumberOfMaterials)
    GetNumberOfMaterials = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetNumberOfMaterials)
    SetOptimizeWithRestarts = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetOptimizeWithRestarts)
    GetOptimizeWithRestarts = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetOptimizeWithRestarts)
    SetThresholds = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetThresholds)
    GetThresholds = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetThresholds)
    SetNumberOfSpectralBins = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetNumberOfSpectralBins)
    GetNumberOfSpectralBins = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetNumberOfSpectralBins)
    SetOutputInverseCramerRaoLowerBound = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetOutputInverseCramerRaoLowerBound)
    GetOutputInverseCramerRaoLowerBound = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetOutputInverseCramerRaoLowerBound)
    SetOutputFischerMatrix = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetOutputFischerMatrix)
    GetOutputFischerMatrix = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetOutputFischerMatrix)
    SetLogTransformEachBin = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetLogTransformEachBin)
    GetLogTransformEachBin = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetLogTransformEachBin)
    SetGuessInitialization = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetGuessInitialization)
    GetGuessInitialization = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetGuessInitialization)
    SetIsSpectralCT = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_SetIsSpectralCT)
    GetIsSpectralCT = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_GetIsSpectralCT)
    __swig_destroy__ = _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.delete_rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2
    cast = _swig_new_static_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_cast)

    def New(*args, **kargs):
        """New() -> rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2

        Create a new object of the class rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2 in _rtkSimplexSpectralProjectionsDecompositionImageFilterPython:
_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_swigregister(rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2___New_orig__ = _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2___New_orig__
rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_cast = _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVID3VID3VIF2IF2IF2_cast


def rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_New():
    return rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.New()

class rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2(itk.itkImageToImageFilterAPython.itkImageToImageFilterVIF3VIF3):
    r"""Proxy of C++ rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2___New_orig__)
    Clone = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_Clone)
    SetInputDecomposedProjections = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetInputDecomposedProjections)
    GetInputDecomposedProjections = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetInputDecomposedProjections)
    SetInputMeasuredProjections = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetInputMeasuredProjections)
    GetInputMeasuredProjections = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetInputMeasuredProjections)
    SetDetectorResponse = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetDetectorResponse)
    GetDetectorResponse = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetDetectorResponse)
    SetMaterialAttenuations = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetMaterialAttenuations)
    GetMaterialAttenuations = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetMaterialAttenuations)
    SetInputIncidentSpectrum = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetInputIncidentSpectrum)
    SetInputSecondIncidentSpectrum = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetInputSecondIncidentSpectrum)
    GetInputIncidentSpectrum = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetInputIncidentSpectrum)
    GetInputSecondIncidentSpectrum = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetInputSecondIncidentSpectrum)
    GetNumberOfIterations = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetNumberOfIterations)
    SetNumberOfIterations = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetNumberOfIterations)
    SetNumberOfEnergies = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetNumberOfEnergies)
    GetNumberOfEnergies = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetNumberOfEnergies)
    SetNumberOfMaterials = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetNumberOfMaterials)
    GetNumberOfMaterials = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetNumberOfMaterials)
    SetOptimizeWithRestarts = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetOptimizeWithRestarts)
    GetOptimizeWithRestarts = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetOptimizeWithRestarts)
    SetThresholds = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetThresholds)
    GetThresholds = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetThresholds)
    SetNumberOfSpectralBins = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetNumberOfSpectralBins)
    GetNumberOfSpectralBins = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetNumberOfSpectralBins)
    SetOutputInverseCramerRaoLowerBound = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetOutputInverseCramerRaoLowerBound)
    GetOutputInverseCramerRaoLowerBound = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetOutputInverseCramerRaoLowerBound)
    SetOutputFischerMatrix = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetOutputFischerMatrix)
    GetOutputFischerMatrix = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetOutputFischerMatrix)
    SetLogTransformEachBin = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetLogTransformEachBin)
    GetLogTransformEachBin = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetLogTransformEachBin)
    SetGuessInitialization = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetGuessInitialization)
    GetGuessInitialization = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetGuessInitialization)
    SetIsSpectralCT = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_SetIsSpectralCT)
    GetIsSpectralCT = _swig_new_instance_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_GetIsSpectralCT)
    __swig_destroy__ = _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.delete_rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2
    cast = _swig_new_static_method(_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_cast)

    def New(*args, **kargs):
        """New() -> rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2

        Create a new object of the class rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2 in _rtkSimplexSpectralProjectionsDecompositionImageFilterPython:
_rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_swigregister(rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2)
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2___New_orig__ = _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2___New_orig__
rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_cast = _rtkSimplexSpectralProjectionsDecompositionImageFilterPython.rtkSimplexSpectralProjectionsDecompositionImageFilterVIF3VIF3VIF2IF2IF2_cast


import itkHelpers
@itkHelpers.accept_numpy_array_like_xarray
def simplex_spectral_projections_decomposition_image_filter(*args, **kwargs):
    """Procedural interface for SimplexSpectralProjectionsDecompositionImageFilter"""
    import itk
    instance = itk.SimplexSpectralProjectionsDecompositionImageFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def simplex_spectral_projections_decomposition_image_filter_init_docstring():
    import itk
    import itkTemplate
    import itkHelpers
    if isinstance(itk.SimplexSpectralProjectionsDecompositionImageFilter, itkTemplate.itkTemplate):
        filter_object = itk.SimplexSpectralProjectionsDecompositionImageFilter.values()[0]
    else:
        filter_object = itk.SimplexSpectralProjectionsDecompositionImageFilter

    simplex_spectral_projections_decomposition_image_filter.__doc__ = filter_object.__doc__
    simplex_spectral_projections_decomposition_image_filter.__doc__ += "\n Args are Input(s) to the filter.\n"
    simplex_spectral_projections_decomposition_image_filter.__doc__ += "\n Available Keyword Arguments:\n"
    if isinstance(itk.SimplexSpectralProjectionsDecompositionImageFilter, itkTemplate.itkTemplate):
        simplex_spectral_projections_decomposition_image_filter.__doc__ += itkHelpers.filter_args(filter_object)[0]
        simplex_spectral_projections_decomposition_image_filter.__doc__ += "\n"
        simplex_spectral_projections_decomposition_image_filter.__doc__ += itkHelpers.filter_args(filter_object)[1]
    else:
        simplex_spectral_projections_decomposition_image_filter.__doc__ += "".join([
            "  " + itkHelpers.camel_to_snake_case(item[3:]) + "\n"
            for item in dir(filter_object)
            if item.startswith("Set")])



