# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


from . import _RTKPython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rtkThreeDCircularProjectionGeometryXMLFileReaderPython
else:
    import _rtkThreeDCircularProjectionGeometryXMLFileReaderPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _rtkThreeDCircularProjectionGeometryXMLFileReaderPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _rtkThreeDCircularProjectionGeometryXMLFileReaderPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import itk.rtkThreeDCircularProjectionGeometryPython
import itk.rtkProjectionGeometryPython
import itk.ITKCommonBasePython
import itk.pyBasePython
import itk.itkMatrixPython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.stdcomplexPython
import itk.itkPointPython
import itk.vnl_vector_refPython
import itk.itkVectorPython
import itk.itkFixedArrayPython
import itk.itkCovariantVectorPython
import itk.vnl_matrix_fixedPython
class itkXMLFile(itk.ITKCommonBasePython.itkLightProcessObject):
    r"""Proxy of C++ itkXMLFile class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    SetFilename = _swig_new_instance_method(_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.itkXMLFile_SetFilename)
    GetFilename = _swig_new_instance_method(_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.itkXMLFile_GetFilename)
    CanReadFile = _swig_new_instance_method(_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.itkXMLFile_CanReadFile)
    GenerateOutputInformation = _swig_new_instance_method(_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.itkXMLFile_GenerateOutputInformation)
    StartElement = _swig_new_instance_method(_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.itkXMLFile_StartElement)
    EndElement = _swig_new_instance_method(_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.itkXMLFile_EndElement)
    CharacterDataHandler = _swig_new_instance_method(_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.itkXMLFile_CharacterDataHandler)

# Register itkXMLFile in _rtkThreeDCircularProjectionGeometryXMLFileReaderPython:
_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.itkXMLFile_swigregister(itkXMLFile)

class itkXMLReader3DCPG(itkXMLFile):
    r"""Proxy of C++ itkXMLReader3DCPG class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    SetOutputObject = _swig_new_instance_method(_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.itkXMLReader3DCPG_SetOutputObject)
    GetOutputObject = _swig_new_instance_method(_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.itkXMLReader3DCPG_GetOutputObject)

# Register itkXMLReader3DCPG in _rtkThreeDCircularProjectionGeometryXMLFileReaderPython:
_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.itkXMLReader3DCPG_swigregister(itkXMLReader3DCPG)


def rtkThreeDCircularProjectionGeometryXMLFileReader_New():
    return rtkThreeDCircularProjectionGeometryXMLFileReader.New()

class rtkThreeDCircularProjectionGeometryXMLFileReader(itkXMLReader3DCPG):
    r"""Proxy of C++ rtkThreeDCircularProjectionGeometryXMLFileReader class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.rtkThreeDCircularProjectionGeometryXMLFileReader___New_orig__)
    Clone = _swig_new_instance_method(_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.rtkThreeDCircularProjectionGeometryXMLFileReader_Clone)
    GetModifiableGeometry = _swig_new_instance_method(_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.rtkThreeDCircularProjectionGeometryXMLFileReader_GetModifiableGeometry)
    GetGeometry = _swig_new_instance_method(_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.rtkThreeDCircularProjectionGeometryXMLFileReader_GetGeometry)
    __swig_destroy__ = _rtkThreeDCircularProjectionGeometryXMLFileReaderPython.delete_rtkThreeDCircularProjectionGeometryXMLFileReader
    cast = _swig_new_static_method(_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.rtkThreeDCircularProjectionGeometryXMLFileReader_cast)

    def New(*args, **kargs):
        """New() -> rtkThreeDCircularProjectionGeometryXMLFileReader

        Create a new object of the class rtkThreeDCircularProjectionGeometryXMLFileReader and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkThreeDCircularProjectionGeometryXMLFileReader.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkThreeDCircularProjectionGeometryXMLFileReader.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkThreeDCircularProjectionGeometryXMLFileReader.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkThreeDCircularProjectionGeometryXMLFileReader in _rtkThreeDCircularProjectionGeometryXMLFileReaderPython:
_rtkThreeDCircularProjectionGeometryXMLFileReaderPython.rtkThreeDCircularProjectionGeometryXMLFileReader_swigregister(rtkThreeDCircularProjectionGeometryXMLFileReader)
rtkThreeDCircularProjectionGeometryXMLFileReader___New_orig__ = _rtkThreeDCircularProjectionGeometryXMLFileReaderPython.rtkThreeDCircularProjectionGeometryXMLFileReader___New_orig__
rtkThreeDCircularProjectionGeometryXMLFileReader_cast = _rtkThreeDCircularProjectionGeometryXMLFileReaderPython.rtkThreeDCircularProjectionGeometryXMLFileReader_cast



