
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-19T22:37:53+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ce55c5217a85879d1df7777d2f4eb91773b269fa",
 "version": "v0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
