
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-26T21:33:58+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "91be4ba4a72d3ebf64dbcf1cab7ce904f151df49",
 "version": "0.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
