# coding: utf-8

"""
    BIMData API

    BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@bimdata.io
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from bimdata_api_client.configuration import Configuration


class Line(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'end_point': 'Point',
        'start_point': 'Point'
    }

    attribute_map = {
        'end_point': 'end_point',
        'start_point': 'start_point'
    }

    def __init__(self, end_point=None, start_point=None, local_vars_configuration=None):  # noqa: E501
        """Line - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._end_point = None
        self._start_point = None
        self.discriminator = None

        self.end_point = end_point
        self.start_point = start_point

    @property
    def end_point(self):
        """Gets the end_point of this Line.  # noqa: E501


        :return: The end_point of this Line.  # noqa: E501
        :rtype: Point
        """
        return self._end_point

    @end_point.setter
    def end_point(self, end_point):
        """Sets the end_point of this Line.


        :param end_point: The end_point of this Line.  # noqa: E501
        :type: Point
        """
        if self.local_vars_configuration.client_side_validation and end_point is None:  # noqa: E501
            raise ValueError("Invalid value for `end_point`, must not be `None`")  # noqa: E501

        self._end_point = end_point

    @property
    def start_point(self):
        """Gets the start_point of this Line.  # noqa: E501


        :return: The start_point of this Line.  # noqa: E501
        :rtype: Point
        """
        return self._start_point

    @start_point.setter
    def start_point(self, start_point):
        """Sets the start_point of this Line.


        :param start_point: The start_point of this Line.  # noqa: E501
        :type: Point
        """
        if self.local_vars_configuration.client_side_validation and start_point is None:  # noqa: E501
            raise ValueError("Invalid value for `start_point`, must not be `None`")  # noqa: E501

        self._start_point = start_point

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Line):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Line):
            return True

        return self.to_dict() != other.to_dict()
