# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PLANCK_CONSTANT": "coloured_spectra.ipynb",
         "SPEED_OF_LIGHT": "coloured_spectra.ipynb",
         "BOLTZMAN_CONSTANT": "coloured_spectra.ipynb",
         "Blackbody": "coloured_spectra.ipynb",
         "piecewise_Guass": "coloured_spectra.ipynb",
         "wavelength2xyz": "coloured_spectra.ipynb",
         "plot_cie_xyz_matching_functions": "coloured_spectra.ipynb",
         "xyz2sRGB": "coloured_spectra.ipynb",
         "plot_colour": "coloured_spectra.ipynb",
         "sRGB2hex": "coloured_spectra.ipynb",
         "plot_wavelength_colours": "coloured_spectra.ipynb",
         "wavelength_intensity2hsv": "coloured_spectra.ipynb",
         "hsv_map": "coloured_spectra.ipynb",
         "plot_hsv_LUT_spectrum": "coloured_spectra.ipynb",
         "colour_hyperspectral_line": "coloured_spectra.ipynb",
         "spectra2sRGB": "coloured_spectra.ipynb",
         "hyperspec_line2colour": "coloured_spectra.ipynb"}

modules = ["coloured_spectra.py"]

doc_url = "https://YiweiMao.github.io/coloured_spectra/"

git_url = "https://github.com/YiweiMao/coloured_spectra/tree/master/"

def custom_doc_links(name): return None
