import pygraphviz as gv
from pyfsa.lib.types import TransitionsTable as TransitionsTable
from typing import List, Optional

def get_state_graph(transitions: TransitionsTable, start: Optional[str]=..., end: Optional[str]=..., nodes: Optional[List[str]]=..., name: str=..., draw: bool=..., engine: str=...) -> gv.AGraph: ...
def verify_string(string: str, starting_state: str, final_state: str, transitions: TransitionsTable) -> bool: ...
def render_string_graph(string: str, start: str, end: str, transitions: TransitionsTable, name: str=..., draw: bool=..., engine: str=...) -> gv.AGraph: ...
