
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-24T21:43:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d12d030b3e14595794ffa124eee33bfb030626d",
 "version": "2.8.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
