#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['transpak']

package_data = \
{'': ['*']}

setup(name='transpak',
      version='0.2.0',
      description='Binary packaging and compression library for PQM-800 transient data ',
      author='Christoph Kattmann',
      author_email='christoph.kattmann@bss-hs.de',
      url=None,
      packages=packages,
      package_data=package_data,
     )
