# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        MainWindow.setMaximumSize(QtCore.QSize(500, 640))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/Bus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.vericallayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.vericallayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vericallayout.setContentsMargins(9, 9, 11, 11)
        self.vericallayout.setSpacing(9)
        self.vericallayout.setObjectName("vericallayout")
        self.frame_commands = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_commands.sizePolicy().hasHeightForWidth())
        self.frame_commands.setSizePolicy(sizePolicy)
        self.frame_commands.setMinimumSize(QtCore.QSize(482, 40))
        self.frame_commands.setMaximumSize(QtCore.QSize(482, 40))
        self.frame_commands.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_commands.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_commands.setObjectName("frame_commands")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_commands)
        self.horizontalLayout_5.setContentsMargins(11, 6, 11, 6)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblModbusMode = QtWidgets.QLabel(self.frame_commands)
        self.lblModbusMode.setObjectName("lblModbusMode")
        self.horizontalLayout_5.addWidget(self.lblModbusMode)
        self.cmbModbusMode = QtWidgets.QComboBox(self.frame_commands)
        self.cmbModbusMode.setMinimumSize(QtCore.QSize(0, 24))
        self.cmbModbusMode.setObjectName("cmbModbusMode")
        self.cmbModbusMode.addItem("")
        self.cmbModbusMode.addItem("")
        self.horizontalLayout_5.addWidget(self.cmbModbusMode)
        self.lblSlave = QtWidgets.QLabel(self.frame_commands)
        self.lblSlave.setObjectName("lblSlave")
        self.horizontalLayout_5.addWidget(self.lblSlave)
        self.sbSlaveID = QtWidgets.QSpinBox(self.frame_commands)
        self.sbSlaveID.setMinimumSize(QtCore.QSize(0, 24))
        self.sbSlaveID.setMinimum(1)
        self.sbSlaveID.setMaximum(247)
        self.sbSlaveID.setObjectName("sbSlaveID")
        self.horizontalLayout_5.addWidget(self.sbSlaveID)
        self.lblSimCycle = QtWidgets.QLabel(self.frame_commands)
        self.lblSimCycle.setObjectName("lblSimCycle")
        self.horizontalLayout_5.addWidget(self.lblSimCycle)
        self.spInterval = QtWidgets.QSpinBox(self.frame_commands)
        self.spInterval.setMinimumSize(QtCore.QSize(0, 24))
        self.spInterval.setMinimum(1000)
        self.spInterval.setMaximum(10000)
        self.spInterval.setSingleStep(500)
        self.spInterval.setProperty("value", 5000)
        self.spInterval.setObjectName("spInterval")
        self.horizontalLayout_5.addWidget(self.spInterval)
        self.vericallayout.addWidget(self.frame_commands)
        self.tabIOs = QtWidgets.QTabWidget(self.centralWidget)
        self.tabIOs.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabIOs.sizePolicy().hasHeightForWidth())
        self.tabIOs.setSizePolicy(sizePolicy)
        self.tabIOs.setMinimumSize(QtCore.QSize(0, 0))
        self.tabIOs.setObjectName("tabIOs")
        self.tabCoils = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabCoils.sizePolicy().hasHeightForWidth())
        self.tabCoils.setSizePolicy(sizePolicy)
        self.tabCoils.setObjectName("tabCoils")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabCoils)
        self.verticalLayout.setContentsMargins(11, 9, 11, 9)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.tabCoils)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setContentsMargins(11, 6, 11, 6)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pbResetDO = QtWidgets.QPushButton(self.frame)
        self.pbResetDO.setMinimumSize(QtCore.QSize(48, 0))
        self.pbResetDO.setMaximumSize(QtCore.QSize(48, 16777215))
        self.pbResetDO.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/edit-clear-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbResetDO.setIcon(icon1)
        self.pbResetDO.setObjectName("pbResetDO")
        self.horizontalLayout_6.addWidget(self.pbResetDO)
        self.lblCoilsStartAddr = QtWidgets.QLabel(self.frame)
        self.lblCoilsStartAddr.setObjectName("lblCoilsStartAddr")
        self.horizontalLayout_6.addWidget(self.lblCoilsStartAddr)
        self.sbCoilsStartAddr = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbCoilsStartAddr.sizePolicy().hasHeightForWidth())
        self.sbCoilsStartAddr.setSizePolicy(sizePolicy)
        self.sbCoilsStartAddr.setMinimumSize(QtCore.QSize(50, 0))
        self.sbCoilsStartAddr.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbCoilsStartAddr.setMinimum(0)
        self.sbCoilsStartAddr.setMaximum(65535)
        self.sbCoilsStartAddr.setSingleStep(10)
        self.sbCoilsStartAddr.setProperty("value", 0)
        self.sbCoilsStartAddr.setObjectName("sbCoilsStartAddr")
        self.horizontalLayout_6.addWidget(self.sbCoilsStartAddr)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.sbNoOfCoils = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbNoOfCoils.sizePolicy().hasHeightForWidth())
        self.sbNoOfCoils.setSizePolicy(sizePolicy)
        self.sbNoOfCoils.setMinimumSize(QtCore.QSize(50, 0))
        self.sbNoOfCoils.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbNoOfCoils.setMinimum(1)
        self.sbNoOfCoils.setMaximum(65535)
        self.sbNoOfCoils.setSingleStep(10)
        self.sbNoOfCoils.setProperty("value", 50)
        self.sbNoOfCoils.setObjectName("sbNoOfCoils")
        self.horizontalLayout_6.addWidget(self.sbNoOfCoils)
        self.chkSimCoils = QtWidgets.QCheckBox(self.frame)
        self.chkSimCoils.setEnabled(False)
        self.chkSimCoils.setObjectName("chkSimCoils")
        self.horizontalLayout_6.addWidget(self.chkSimCoils)
        self.verticalLayout.addWidget(self.frame)
        self.tvCoilsData = QtWidgets.QTableView(self.tabCoils)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvCoilsData.sizePolicy().hasHeightForWidth())
        self.tvCoilsData.setSizePolicy(sizePolicy)
        self.tvCoilsData.setMinimumSize(QtCore.QSize(450, 0))
        self.tvCoilsData.setCornerButtonEnabled(False)
        self.tvCoilsData.setObjectName("tvCoilsData")
        self.tvCoilsData.horizontalHeader().setVisible(False)
        self.tvCoilsData.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tvCoilsData)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/DO.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabIOs.addTab(self.tabCoils, icon2, "")
        self.tabDiscreteInputs = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabDiscreteInputs.sizePolicy().hasHeightForWidth())
        self.tabDiscreteInputs.setSizePolicy(sizePolicy)
        self.tabDiscreteInputs.setObjectName("tabDiscreteInputs")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabDiscreteInputs)
        self.verticalLayout_2.setContentsMargins(11, 9, 11, 9)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.tabDiscreteInputs)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(11, 6, 11, 6)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbResetDI = QtWidgets.QPushButton(self.frame_2)
        self.pbResetDI.setMinimumSize(QtCore.QSize(48, 0))
        self.pbResetDI.setMaximumSize(QtCore.QSize(48, 16777215))
        self.pbResetDI.setText("")
        self.pbResetDI.setIcon(icon1)
        self.pbResetDI.setObjectName("pbResetDI")
        self.horizontalLayout.addWidget(self.pbResetDI)
        self.lblDigInputsStartAddr = QtWidgets.QLabel(self.frame_2)
        self.lblDigInputsStartAddr.setObjectName("lblDigInputsStartAddr")
        self.horizontalLayout.addWidget(self.lblDigInputsStartAddr)
        self.sbDigInputsstartAddr = QtWidgets.QSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbDigInputsstartAddr.sizePolicy().hasHeightForWidth())
        self.sbDigInputsstartAddr.setSizePolicy(sizePolicy)
        self.sbDigInputsstartAddr.setMinimumSize(QtCore.QSize(50, 0))
        self.sbDigInputsstartAddr.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbDigInputsstartAddr.setMinimum(0)
        self.sbDigInputsstartAddr.setMaximum(65535)
        self.sbDigInputsstartAddr.setSingleStep(10)
        self.sbDigInputsstartAddr.setProperty("value", 0)
        self.sbDigInputsstartAddr.setObjectName("sbDigInputsstartAddr")
        self.horizontalLayout.addWidget(self.sbDigInputsstartAddr)
        self.lblNoOfDigInputs = QtWidgets.QLabel(self.frame_2)
        self.lblNoOfDigInputs.setObjectName("lblNoOfDigInputs")
        self.horizontalLayout.addWidget(self.lblNoOfDigInputs)
        self.sbNoOfDigInputs = QtWidgets.QSpinBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbNoOfDigInputs.sizePolicy().hasHeightForWidth())
        self.sbNoOfDigInputs.setSizePolicy(sizePolicy)
        self.sbNoOfDigInputs.setMinimumSize(QtCore.QSize(50, 0))
        self.sbNoOfDigInputs.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbNoOfDigInputs.setMinimum(1)
        self.sbNoOfDigInputs.setMaximum(65535)
        self.sbNoOfDigInputs.setSingleStep(10)
        self.sbNoOfDigInputs.setProperty("value", 50)
        self.sbNoOfDigInputs.setObjectName("sbNoOfDigInputs")
        self.horizontalLayout.addWidget(self.sbNoOfDigInputs)
        self.chkSimDisInputs = QtWidgets.QCheckBox(self.frame_2)
        self.chkSimDisInputs.setEnabled(False)
        self.chkSimDisInputs.setObjectName("chkSimDisInputs")
        self.horizontalLayout.addWidget(self.chkSimDisInputs)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.tvDiscreteInputsData = QtWidgets.QTableView(self.tabDiscreteInputs)
        self.tvDiscreteInputsData.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvDiscreteInputsData.sizePolicy().hasHeightForWidth())
        self.tvDiscreteInputsData.setSizePolicy(sizePolicy)
        self.tvDiscreteInputsData.setMinimumSize(QtCore.QSize(450, 0))
        self.tvDiscreteInputsData.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tvDiscreteInputsData.setCornerButtonEnabled(False)
        self.tvDiscreteInputsData.setObjectName("tvDiscreteInputsData")
        self.tvDiscreteInputsData.horizontalHeader().setVisible(False)
        self.tvDiscreteInputsData.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tvDiscreteInputsData)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/DI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabIOs.addTab(self.tabDiscreteInputs, icon3, "")
        self.tabInputRegisters = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabInputRegisters.sizePolicy().hasHeightForWidth())
        self.tabInputRegisters.setSizePolicy(sizePolicy)
        self.tabInputRegisters.setObjectName("tabInputRegisters")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabInputRegisters)
        self.verticalLayout_6.setContentsMargins(11, 9, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.tabInputRegisters)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(11, 6, 11, 6)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbResetAI = QtWidgets.QPushButton(self.frame_3)
        self.pbResetAI.setMinimumSize(QtCore.QSize(48, 0))
        self.pbResetAI.setMaximumSize(QtCore.QSize(48, 16777215))
        self.pbResetAI.setText("")
        self.pbResetAI.setIcon(icon1)
        self.pbResetAI.setObjectName("pbResetAI")
        self.horizontalLayout_2.addWidget(self.pbResetAI)
        self.lblInputRegsStartAddr = QtWidgets.QLabel(self.frame_3)
        self.lblInputRegsStartAddr.setObjectName("lblInputRegsStartAddr")
        self.horizontalLayout_2.addWidget(self.lblInputRegsStartAddr)
        self.sbInputRegsStartAddr = QtWidgets.QSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbInputRegsStartAddr.sizePolicy().hasHeightForWidth())
        self.sbInputRegsStartAddr.setSizePolicy(sizePolicy)
        self.sbInputRegsStartAddr.setMinimumSize(QtCore.QSize(50, 0))
        self.sbInputRegsStartAddr.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbInputRegsStartAddr.setMinimum(0)
        self.sbInputRegsStartAddr.setMaximum(65535)
        self.sbInputRegsStartAddr.setSingleStep(10)
        self.sbInputRegsStartAddr.setProperty("value", 0)
        self.sbInputRegsStartAddr.setObjectName("sbInputRegsStartAddr")
        self.horizontalLayout_2.addWidget(self.sbInputRegsStartAddr)
        self.lblNoOfInputRegs = QtWidgets.QLabel(self.frame_3)
        self.lblNoOfInputRegs.setObjectName("lblNoOfInputRegs")
        self.horizontalLayout_2.addWidget(self.lblNoOfInputRegs)
        self.sbNoOfInputRegs = QtWidgets.QSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbNoOfInputRegs.sizePolicy().hasHeightForWidth())
        self.sbNoOfInputRegs.setSizePolicy(sizePolicy)
        self.sbNoOfInputRegs.setMinimumSize(QtCore.QSize(50, 0))
        self.sbNoOfInputRegs.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbNoOfInputRegs.setMinimum(1)
        self.sbNoOfInputRegs.setMaximum(65535)
        self.sbNoOfInputRegs.setSingleStep(10)
        self.sbNoOfInputRegs.setProperty("value", 50)
        self.sbNoOfInputRegs.setObjectName("sbNoOfInputRegs")
        self.horizontalLayout_2.addWidget(self.sbNoOfInputRegs)
        self.chkSimInputRegs = QtWidgets.QCheckBox(self.frame_3)
        self.chkSimInputRegs.setEnabled(False)
        self.chkSimInputRegs.setObjectName("chkSimInputRegs")
        self.horizontalLayout_2.addWidget(self.chkSimInputRegs)
        self.cmbInputRegsType = QtWidgets.QComboBox(self.frame_3)
        self.cmbInputRegsType.setMaxVisibleItems(2)
        self.cmbInputRegsType.setObjectName("cmbInputRegsType")
        self.cmbInputRegsType.addItem("")
        self.cmbInputRegsType.addItem("")
        self.horizontalLayout_2.addWidget(self.cmbInputRegsType)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.tvInputRegistersData = QtWidgets.QTableView(self.tabInputRegisters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvInputRegistersData.sizePolicy().hasHeightForWidth())
        self.tvInputRegistersData.setSizePolicy(sizePolicy)
        self.tvInputRegistersData.setMinimumSize(QtCore.QSize(450, 0))
        self.tvInputRegistersData.setCornerButtonEnabled(False)
        self.tvInputRegistersData.setObjectName("tvInputRegistersData")
        self.tvInputRegistersData.horizontalHeader().setVisible(False)
        self.tvInputRegistersData.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.tvInputRegistersData)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/AI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabIOs.addTab(self.tabInputRegisters, icon4, "")
        self.tabHoldingRegisters = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabHoldingRegisters.sizePolicy().hasHeightForWidth())
        self.tabHoldingRegisters.setSizePolicy(sizePolicy)
        self.tabHoldingRegisters.setObjectName("tabHoldingRegisters")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabHoldingRegisters)
        self.verticalLayout_7.setContentsMargins(11, 9, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.tabHoldingRegisters)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(11, 6, 11, 6)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pbResetAO = QtWidgets.QPushButton(self.frame_4)
        self.pbResetAO.setMinimumSize(QtCore.QSize(48, 0))
        self.pbResetAO.setMaximumSize(QtCore.QSize(48, 16777215))
        self.pbResetAO.setText("")
        self.pbResetAO.setIcon(icon1)
        self.pbResetAO.setObjectName("pbResetAO")
        self.horizontalLayout_4.addWidget(self.pbResetAO)
        self.lblHoldRegsStarAddr = QtWidgets.QLabel(self.frame_4)
        self.lblHoldRegsStarAddr.setObjectName("lblHoldRegsStarAddr")
        self.horizontalLayout_4.addWidget(self.lblHoldRegsStarAddr)
        self.sbHoldingRegsStartAddr = QtWidgets.QSpinBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbHoldingRegsStartAddr.sizePolicy().hasHeightForWidth())
        self.sbHoldingRegsStartAddr.setSizePolicy(sizePolicy)
        self.sbHoldingRegsStartAddr.setMinimumSize(QtCore.QSize(50, 0))
        self.sbHoldingRegsStartAddr.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbHoldingRegsStartAddr.setMinimum(0)
        self.sbHoldingRegsStartAddr.setMaximum(65535)
        self.sbHoldingRegsStartAddr.setSingleStep(10)
        self.sbHoldingRegsStartAddr.setProperty("value", 0)
        self.sbHoldingRegsStartAddr.setObjectName("sbHoldingRegsStartAddr")
        self.horizontalLayout_4.addWidget(self.sbHoldingRegsStartAddr)
        self.lblHoldRegs = QtWidgets.QLabel(self.frame_4)
        self.lblHoldRegs.setObjectName("lblHoldRegs")
        self.horizontalLayout_4.addWidget(self.lblHoldRegs)
        self.sbNoOfHoldingRegs = QtWidgets.QSpinBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbNoOfHoldingRegs.sizePolicy().hasHeightForWidth())
        self.sbNoOfHoldingRegs.setSizePolicy(sizePolicy)
        self.sbNoOfHoldingRegs.setMinimumSize(QtCore.QSize(50, 0))
        self.sbNoOfHoldingRegs.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbNoOfHoldingRegs.setMinimum(1)
        self.sbNoOfHoldingRegs.setMaximum(65535)
        self.sbNoOfHoldingRegs.setSingleStep(10)
        self.sbNoOfHoldingRegs.setProperty("value", 50)
        self.sbNoOfHoldingRegs.setObjectName("sbNoOfHoldingRegs")
        self.horizontalLayout_4.addWidget(self.sbNoOfHoldingRegs)
        self.chkSimHoldRegs = QtWidgets.QCheckBox(self.frame_4)
        self.chkSimHoldRegs.setEnabled(False)
        self.chkSimHoldRegs.setObjectName("chkSimHoldRegs")
        self.horizontalLayout_4.addWidget(self.chkSimHoldRegs)
        self.cmbHoldRegsType = QtWidgets.QComboBox(self.frame_4)
        self.cmbHoldRegsType.setMaxVisibleItems(2)
        self.cmbHoldRegsType.setObjectName("cmbHoldRegsType")
        self.cmbHoldRegsType.addItem("")
        self.cmbHoldRegsType.addItem("")
        self.horizontalLayout_4.addWidget(self.cmbHoldRegsType)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.tvHoldingRegistersData = QtWidgets.QTableView(self.tabHoldingRegisters)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvHoldingRegistersData.sizePolicy().hasHeightForWidth())
        self.tvHoldingRegistersData.setSizePolicy(sizePolicy)
        self.tvHoldingRegistersData.setMinimumSize(QtCore.QSize(450, 0))
        self.tvHoldingRegistersData.setCornerButtonEnabled(False)
        self.tvHoldingRegistersData.setObjectName("tvHoldingRegistersData")
        self.tvHoldingRegistersData.horizontalHeader().setVisible(False)
        self.tvHoldingRegistersData.verticalHeader().setVisible(False)
        self.verticalLayout_7.addWidget(self.tvHoldingRegistersData)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/AO.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabIOs.addTab(self.tabHoldingRegisters, icon5, "")
        self.vericallayout.addWidget(self.tabIOs)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuCommands = QtWidgets.QMenu(self.menuBar)
        self.menuCommands.setObjectName("menuCommands")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/exit-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon6)
        self.actionExit.setIconVisibleInMenu(True)
        self.actionExit.setObjectName("actionExit")
        self.actionSerial_RTU = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/serial-pot-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSerial_RTU.setIcon(icon7)
        self.actionSerial_RTU.setIconVisibleInMenu(True)
        self.actionSerial_RTU.setObjectName("actionSerial_RTU")
        self.actionTCP = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/ethernet-port-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTCP.setIcon(icon8)
        self.actionTCP.setIconVisibleInMenu(True)
        self.actionTCP.setObjectName("actionTCP")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img/info-sign-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon9)
        self.actionAbout.setIconVisibleInMenu(True)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/img/options-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon10)
        self.actionSettings.setIconVisibleInMenu(True)
        self.actionSettings.setObjectName("actionSettings")
        self.actionBus_Monitor = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/img/TV-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBus_Monitor.setIcon(icon11)
        self.actionBus_Monitor.setObjectName("actionBus_Monitor")
        self.actionReset_Counters = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/img/reset-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReset_Counters.setIcon(icon12)
        self.actionReset_Counters.setObjectName("actionReset_Counters")
        self.actionLog = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/img/text-x-log-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLog.setIcon(icon13)
        self.actionLog.setObjectName("actionLog")
        self.actionModbus_Manual = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/img/help-desk-icon-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModbus_Manual.setIcon(icon14)
        self.actionModbus_Manual.setObjectName("actionModbus_Manual")
        self.actionLoad_Session = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/img/document-import-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_Session.setIcon(icon15)
        self.actionLoad_Session.setObjectName("actionLoad_Session")
        self.actionSave_Session = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/img/document-export-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_Session.setIcon(icon16)
        self.actionSave_Session.setObjectName("actionSave_Session")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setCheckable(True)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/img/plug-disconnect-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon17.addPixmap(QtGui.QPixmap(":/img/plug-connect-16.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionConnect.setIcon(icon17)
        self.actionConnect.setObjectName("actionConnect")
        self.actionHeaders = QtWidgets.QAction(MainWindow)
        self.actionHeaders.setCheckable(True)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/img/Header16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHeaders.setIcon(icon18)
        self.actionHeaders.setObjectName("actionHeaders")
        self.menuFile.addAction(self.actionLoad_Session)
        self.menuFile.addAction(self.actionSave_Session)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionSerial_RTU)
        self.menuOptions.addAction(self.actionTCP)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionModbus_Manual)
        self.menuHelp.addAction(self.actionAbout)
        self.menuView.addAction(self.actionLog)
        self.menuView.addAction(self.actionBus_Monitor)
        self.menuView.addAction(self.actionHeaders)
        self.menuCommands.addAction(self.actionConnect)
        self.menuCommands.addAction(self.actionReset_Counters)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuCommands.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.lblModbusMode.setBuddy(self.cmbModbusMode)
        self.lblSlave.setBuddy(self.sbSlaveID)

        self.retranslateUi(MainWindow)
        self.tabIOs.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pyModSlave"))
        self.lblModbusMode.setText(_translate("MainWindow", "Modbus Mode"))
        self.cmbModbusMode.setItemText(0, _translate("MainWindow", "RTU"))
        self.cmbModbusMode.setItemText(1, _translate("MainWindow", "TCP"))
        self.lblSlave.setText(_translate("MainWindow", "Slave Addr"))
        self.lblSimCycle.setText(_translate("MainWindow", "SimCycle (msec)"))
        self.pbResetDO.setToolTip(_translate("MainWindow", "Reset"))
        self.lblCoilsStartAddr.setText(_translate("MainWindow", "Start Addr"))
        self.label.setText(_translate("MainWindow", "No of Coils"))
        self.chkSimCoils.setText(_translate("MainWindow", "Sim"))
        self.tabIOs.setTabText(self.tabIOs.indexOf(self.tabCoils), _translate("MainWindow", "Coils"))
        self.pbResetDI.setToolTip(_translate("MainWindow", "Reset"))
        self.lblDigInputsStartAddr.setText(_translate("MainWindow", "Start Addr"))
        self.lblNoOfDigInputs.setText(_translate("MainWindow", "No of Inputs"))
        self.chkSimDisInputs.setText(_translate("MainWindow", "Sim"))
        self.tabIOs.setTabText(self.tabIOs.indexOf(self.tabDiscreteInputs), _translate("MainWindow", "Discrete Inputs"))
        self.pbResetAI.setToolTip(_translate("MainWindow", "Reset"))
        self.lblInputRegsStartAddr.setText(_translate("MainWindow", "Start Addr"))
        self.lblNoOfInputRegs.setText(_translate("MainWindow", "No of Regs"))
        self.chkSimInputRegs.setText(_translate("MainWindow", "Sim"))
        self.cmbInputRegsType.setItemText(0, _translate("MainWindow", "Dec"))
        self.cmbInputRegsType.setItemText(1, _translate("MainWindow", "Hex"))
        self.tabIOs.setTabText(self.tabIOs.indexOf(self.tabInputRegisters), _translate("MainWindow", "Input Registers"))
        self.pbResetAO.setToolTip(_translate("MainWindow", "Reset"))
        self.lblHoldRegsStarAddr.setText(_translate("MainWindow", "Start Addr"))
        self.lblHoldRegs.setText(_translate("MainWindow", "No of Regs"))
        self.chkSimHoldRegs.setText(_translate("MainWindow", "Sim"))
        self.cmbHoldRegsType.setItemText(0, _translate("MainWindow", "Dec"))
        self.cmbHoldRegsType.setItemText(1, _translate("MainWindow", "Hex"))
        self.tabIOs.setTabText(self.tabIOs.indexOf(self.tabHoldingRegisters), _translate("MainWindow", "Holding Registers"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuCommands.setTitle(_translate("MainWindow", "Commands"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSerial_RTU.setText(_translate("MainWindow", "Modbus RTU..."))
        self.actionTCP.setText(_translate("MainWindow", "Modbus TCP..."))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionSettings.setText(_translate("MainWindow", "Settings..."))
        self.actionBus_Monitor.setText(_translate("MainWindow", "Bus Monitor"))
        self.actionReset_Counters.setText(_translate("MainWindow", "Reset Counters"))
        self.actionLog.setText(_translate("MainWindow", "Log"))
        self.actionModbus_Manual.setText(_translate("MainWindow", "Modbus Manual"))
        self.actionLoad_Session.setText(_translate("MainWindow", "Load Session..."))
        self.actionSave_Session.setText(_translate("MainWindow", "Save Session..."))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionHeaders.setText(_translate("MainWindow", "Headers"))
import pyModSlaveQt_rc
