# Generated by Django 3.0.4 on 2020-11-13 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenmailbox', '0003_mail_received_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='updated_at',
        ),
    ]
