
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-22T16:13:11-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "f5801560f8c85ce1c821741b1dafcd871f53f1c9",
 "version": "0.13.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
