# coding: utf-8

"""
    AristaFlowREST/ProcessManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_process_manager
from af_process_manager.api.templ_kind_remote_iterator_rest_api import TemplKindRemoteIteratorRestApi  # noqa: E501
from af_process_manager.rest import ApiException


class TestTemplKindRemoteIteratorRestApi(unittest.TestCase):
    """TemplKindRemoteIteratorRestApi unit test stubs"""

    def setUp(self):
        self.api = TemplKindRemoteIteratorRestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_templ_kind_drop(self):
        """Test case for templ_kind_drop

        """
        pass

    def test_templ_kind_get_next(self):
        """Test case for templ_kind_get_next

        """
        pass

    def test_templ_kind_get_previous(self):
        """Test case for templ_kind_get_previous

        """
        pass

    def test_templ_kind_keep_alive(self):
        """Test case for templ_kind_keep_alive

        """
        pass


if __name__ == '__main__':
    unittest.main()
