# coding: utf-8

"""
    AristaFlowREST/WorklistManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from af_worklist_manager.models.client_worklist_callback_data import ClientWorklistCallbackData  # noqa: F401,E501

class ClientWorklistRestCallbackData(ClientWorklistCallbackData):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'worklist_callback': 'str'
    }
    if hasattr(ClientWorklistCallbackData, "swagger_types"):
        swagger_types.update(ClientWorklistCallbackData.swagger_types)

    attribute_map = {
        'worklist_callback': 'worklistCallback'
    }
    if hasattr(ClientWorklistCallbackData, "attribute_map"):
        attribute_map.update(ClientWorklistCallbackData.attribute_map)

    def __init__(self, worklist_callback=None, *args, **kwargs):  # noqa: E501
        """ClientWorklistRestCallbackData - a model defined in Swagger"""  # noqa: E501
        self._worklist_callback = None
        if not(hasattr(self, "discriminator")) or not(self.discriminator):
            self.discriminator = None
        self.worklist_callback = worklist_callback
        ClientWorklistCallbackData.__init__(self, *args, **kwargs)

    @property
    def worklist_callback(self):
        """Gets the worklist_callback of this ClientWorklistRestCallbackData.  # noqa: E501


        :return: The worklist_callback of this ClientWorklistRestCallbackData.  # noqa: E501
        :rtype: str
        """
        return self._worklist_callback

    @worklist_callback.setter
    def worklist_callback(self, worklist_callback):
        """Sets the worklist_callback of this ClientWorklistRestCallbackData.


        :param worklist_callback: The worklist_callback of this ClientWorklistRestCallbackData.  # noqa: E501
        :type: str
        """
        if worklist_callback is None:
            raise ValueError("Invalid value for `worklist_callback`, must not be `None`")  # noqa: E501

        self._worklist_callback = worklist_callback

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClientWorklistRestCallbackData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClientWorklistRestCallbackData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
