
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/mcot/maths:dist

from setuptools import setup

setup(**{
    'author': 'Michiel Cottaar',
    'author_email': 'Michiel.Cottaar@ndcn.ox.ac.uk',
    'classifiers': [
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Operating System :: OS Independent',
    ],
    'description': 'Math functions',
    'license': 'MIT license',
    'long_description': 'Math stuff',
    'name': 'mcot.maths',
    'python_requires': '>=3.6',
    'url': 'https://git.fmrib.ox.ac.uk/ndcn0236/mcot',
    'version': '0.1.0',
    'package_dir': {
        '': 'src',
    },
    'packages': (
        'mcot',
        'mcot.maths',
    ),
    'namespace_packages': (
    ),
    'package_data': {
        'mcot.maths': (
            'README.rst',
            'VERSION',
        ),
    },
    'install_requires': (
        'mcot.utils~=0.1.0',
        'numpy',
    ),
})
