# coding: utf-8

"""
    AristaFlowREST/SimpleProcessImageRenderer

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_simple_process_image_renderer
from af_simple_process_image_renderer.models.process_image_data import ProcessImageData  # noqa: E501
from af_simple_process_image_renderer.rest import ApiException


class TestProcessImageData(unittest.TestCase):
    """ProcessImageData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProcessImageData(self):
        """Test ProcessImageData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_simple_process_image_renderer.models.process_image_data.ProcessImageData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
