from pyfsa.lib.types import TransitionsTable as TransitionsTable
from typing import Any, Dict, List

def convert_csv_file(file_name: str) -> TransitionsTable: ...
def rows_to_transitions(transition_data: Any): ...
def convert_transitions(transitions: TransitionsTable) -> List[Dict[str, str]]: ...
def transitions_to_csv(transitions: TransitionsTable, file_name: str) -> Any: ...
