# coding: utf-8

"""
    AristaFlowREST/RuntimeService

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_runtime_service
from af_runtime_service.models.close_message import CloseMessage  # noqa: E501
from af_runtime_service.rest import ApiException


class TestCloseMessage(unittest.TestCase):
    """CloseMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloseMessage(self):
        """Test CloseMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_runtime_service.models.close_message.CloseMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
