
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-23T09:20:29+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dbf2b3731fef72c3d757dd561da99f0e4045db08",
 "version": "1.1.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
