"""
    kika

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.5.3
    Contact: info@kikapay.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.exact_recurring_payment400_response_errors import ExactRecurringPayment400ResponseErrors


class TestExactRecurringPayment400ResponseErrors(unittest.TestCase):
    """ExactRecurringPayment400ResponseErrors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExactRecurringPayment400ResponseErrors(self):
        """Test ExactRecurringPayment400ResponseErrors"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExactRecurringPayment400ResponseErrors()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
