"""
    kika

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.5.3
    Contact: info@kikapay.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.merchant import Merchant
from openapi_client.model.payment_conditions_single_immediate_payment_multi import PaymentConditionsSingleImmediatePaymentMulti
from openapi_client.model.payment_details import PaymentDetails
from openapi_client.model.payment_single_exact import PaymentSingleExact
from openapi_client.model.qr_code import QrCode
from openapi_client.model.redirect import Redirect
globals()['Merchant'] = Merchant
globals()['PaymentConditionsSingleImmediatePaymentMulti'] = PaymentConditionsSingleImmediatePaymentMulti
globals()['PaymentDetails'] = PaymentDetails
globals()['PaymentSingleExact'] = PaymentSingleExact
globals()['QrCode'] = QrCode
globals()['Redirect'] = Redirect
from openapi_client.model.single_immediate_payment_multi import SingleImmediatePaymentMulti


class TestSingleImmediatePaymentMulti(unittest.TestCase):
    """SingleImmediatePaymentMulti unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleImmediatePaymentMulti(self):
        """Test SingleImmediatePaymentMulti"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SingleImmediatePaymentMulti()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
