"""
    kika

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.5.3
    Contact: info@kikapay.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.reconciliation_payment200_response_merchant_customer import ReconciliationPayment200ResponseMerchantCustomer
globals()['ReconciliationPayment200ResponseMerchantCustomer'] = ReconciliationPayment200ResponseMerchantCustomer
from openapi_client.model.reconciliation_payment200_response_merchant import ReconciliationPayment200ResponseMerchant


class TestReconciliationPayment200ResponseMerchant(unittest.TestCase):
    """ReconciliationPayment200ResponseMerchant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReconciliationPayment200ResponseMerchant(self):
        """Test ReconciliationPayment200ResponseMerchant"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ReconciliationPayment200ResponseMerchant()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
