
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-27T05:19:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "16c322bbdb9907ed5629affee4454cadbd59ea63",
 "version": "0.6.2.post.dev114"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
