# coding: utf-8

"""
    AristaFlowREST/ProcessImageRenderer

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_process_image_renderer
from af_process_image_renderer.models.decision_activity import DecisionActivity  # noqa: E501
from af_process_image_renderer.rest import ApiException


class TestDecisionActivity(unittest.TestCase):
    """DecisionActivity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDecisionActivity(self):
        """Test DecisionActivity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_process_image_renderer.models.decision_activity.DecisionActivity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
