# coding: utf-8

"""
    AristaFlowREST/ProcessImageRenderer

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_process_image_renderer
from af_process_image_renderer.api.process_image_renderer_api import ProcessImageRendererApi  # noqa: E501
from af_process_image_renderer.rest import ApiException


class TestProcessImageRendererApi(unittest.TestCase):
    """ProcessImageRendererApi unit test stubs"""

    def setUp(self):
        self.api = ProcessImageRendererApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_instance(self):
        """Test case for get_instance

        """
        pass

    def test_get_template(self):
        """Test case for get_template

        """
        pass

    def test_render_instance(self):
        """Test case for render_instance

        """
        pass

    def test_render_template(self):
        """Test case for render_template

        """
        pass


if __name__ == '__main__':
    unittest.main()
