# coding: utf-8

"""
    AristaFlowREST/OrgModelManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Body3(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'org_policy': 'str',
        'attr_names': 'list[str]'
    }

    attribute_map = {
        'org_policy': 'orgPolicy',
        'attr_names': 'attrNames'
    }

    def __init__(self, org_policy=None, attr_names=None):  # noqa: E501
        """Body3 - a model defined in Swagger"""  # noqa: E501
        self._org_policy = None
        self._attr_names = None
        if not(hasattr(self, "discriminator")) or not(self.discriminator):
            self.discriminator = None
        self.org_policy = org_policy
        if attr_names is not None:
            self.attr_names = attr_names

    @property
    def org_policy(self):
        """Gets the org_policy of this Body3.  # noqa: E501


        :return: The org_policy of this Body3.  # noqa: E501
        :rtype: str
        """
        return self._org_policy

    @org_policy.setter
    def org_policy(self, org_policy):
        """Sets the org_policy of this Body3.


        :param org_policy: The org_policy of this Body3.  # noqa: E501
        :type: str
        """
        if org_policy is None:
            raise ValueError("Invalid value for `org_policy`, must not be `None`")  # noqa: E501

        self._org_policy = org_policy

    @property
    def attr_names(self):
        """Gets the attr_names of this Body3.  # noqa: E501


        :return: The attr_names of this Body3.  # noqa: E501
        :rtype: list[str]
        """
        return self._attr_names

    @attr_names.setter
    def attr_names(self, attr_names):
        """Sets the attr_names of this Body3.


        :param attr_names: The attr_names of this Body3.  # noqa: E501
        :type: list[str]
        """

        self._attr_names = attr_names

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body3, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body3):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
