# coding: utf-8

"""
    AristaFlowREST/SimpleProcessImageRenderer

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_simple_process_image_renderer
from af_simple_process_image_renderer.models.parameter_type_exception import ParameterTypeException  # noqa: E501
from af_simple_process_image_renderer.rest import ApiException


class TestParameterTypeException(unittest.TestCase):
    """ParameterTypeException unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParameterTypeException(self):
        """Test ParameterTypeException"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_simple_process_image_renderer.models.parameter_type_exception.ParameterTypeException()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
