# coding: utf-8

"""
    AristaFlowREST/ProcessImageRenderer

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_process_image_renderer
from af_process_image_renderer.models.activity_conf_extension import ActivityConfExtension  # noqa: E501
from af_process_image_renderer.rest import ApiException


class TestActivityConfExtension(unittest.TestCase):
    """ActivityConfExtension unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivityConfExtension(self):
        """Test ActivityConfExtension"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_process_image_renderer.models.activity_conf_extension.ActivityConfExtension()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
