
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-26T10:58:39-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "9cd77e0aa24d59fddf534948b9b97dacb0832ed2",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
