# coding: utf-8

"""
    AristaFlowREST/RuntimeManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_remote_html_runtime_manager
from af_remote_html_runtime_manager.models.activity_exec_resumed_data import ActivityExecResumedData  # noqa: E501
from af_remote_html_runtime_manager.rest import ApiException


class TestActivityExecResumedData(unittest.TestCase):
    """ActivityExecResumedData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivityExecResumedData(self):
        """Test ActivityExecResumedData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = af_remote_html_runtime_manager.models.activity_exec_resumed_data.ActivityExecResumedData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
