
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-27T16:56:59+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad6a80f57bdf8dac31d2757d04e4f5f04d2c6adc",
 "version": "0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
