
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "01bb85141408a1dba5023e80e147477d36cd5eaf",
 "version": "2397"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
