# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


from . import _RTKPython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rtkElektaSynergyRawLookupTableImageFilterPython
else:
    import _rtkElektaSynergyRawLookupTableImageFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _rtkElektaSynergyRawLookupTableImageFilterPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _rtkElektaSynergyRawLookupTableImageFilterPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import itk.rtkLookupTableImageFilterPython
import itk.itkInPlaceImageFilterAPython
import itk.itkImageToImageFilterAPython
import itk.itkImagePython
import itk.stdcomplexPython
import itk.pyBasePython
import itk.itkCovariantVectorPython
import itk.vnl_vector_refPython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.itkFixedArrayPython
import itk.itkVectorPython
import itk.itkIndexPython
import itk.itkSizePython
import itk.itkOffsetPython
import itk.itkRGBPixelPython
import itk.itkRGBAPixelPython
import itk.itkMatrixPython
import itk.vnl_matrix_fixedPython
import itk.itkPointPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkImageRegionPython
import itk.ITKCommonBasePython
import itk.itkImageSourcePython
import itk.itkImageSourceCommonPython
import itk.itkVectorImagePython
import itk.itkVariableLengthVectorPython
import itk.itkImageToImageFilterCommonPython
import itk.itkImageToImageFilterBPython
import itk.itkImageRTKPython
import itk.itkImageBaseRTKPython
import itk.itkMatrixRTKPython
import itk.itkCovariantVectorRTKPython
import itk.itkPointRTKPython
import itk.itkImageRegionRTKPython
import itk.itkInPlaceImageFilterRTKPython
import itk.itkImageToImageFilterRTKPython
import itk.itkImageSourceRTKPython

def rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2_New():
    return rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2.New()

class rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2(itk.rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS2IUS2):
    r"""Proxy of C++ rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkElektaSynergyRawLookupTableImageFilterPython.rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2___New_orig__)
    Clone = _swig_new_instance_method(_rtkElektaSynergyRawLookupTableImageFilterPython.rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2_Clone)
    SameTypeCheck = _rtkElektaSynergyRawLookupTableImageFilterPython.rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2_SameTypeCheck
    
    __swig_destroy__ = _rtkElektaSynergyRawLookupTableImageFilterPython.delete_rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2
    cast = _swig_new_static_method(_rtkElektaSynergyRawLookupTableImageFilterPython.rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2_cast)

    def New(*args, **kargs):
        """New() -> rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2

        Create a new object of the class rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2 in _rtkElektaSynergyRawLookupTableImageFilterPython:
_rtkElektaSynergyRawLookupTableImageFilterPython.rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2_swigregister(rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2)
rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2___New_orig__ = _rtkElektaSynergyRawLookupTableImageFilterPython.rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2___New_orig__
rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2_cast = _rtkElektaSynergyRawLookupTableImageFilterPython.rtkElektaSynergyRawLookupTableImageFilterIUS2IUS2_cast


def rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3_New():
    return rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3.New()

class rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3(itk.rtkLookupTableImageFilterPython.rtkLookupTableImageFilterIUS3IUS3):
    r"""Proxy of C++ rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkElektaSynergyRawLookupTableImageFilterPython.rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3___New_orig__)
    Clone = _swig_new_instance_method(_rtkElektaSynergyRawLookupTableImageFilterPython.rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3_Clone)
    SameTypeCheck = _rtkElektaSynergyRawLookupTableImageFilterPython.rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3_SameTypeCheck
    
    __swig_destroy__ = _rtkElektaSynergyRawLookupTableImageFilterPython.delete_rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3
    cast = _swig_new_static_method(_rtkElektaSynergyRawLookupTableImageFilterPython.rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3_cast)

    def New(*args, **kargs):
        """New() -> rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3

        Create a new object of the class rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3 in _rtkElektaSynergyRawLookupTableImageFilterPython:
_rtkElektaSynergyRawLookupTableImageFilterPython.rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3_swigregister(rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3)
rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3___New_orig__ = _rtkElektaSynergyRawLookupTableImageFilterPython.rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3___New_orig__
rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3_cast = _rtkElektaSynergyRawLookupTableImageFilterPython.rtkElektaSynergyRawLookupTableImageFilterIUS3IUS3_cast


import itkHelpers
@itkHelpers.accept_numpy_array_like_xarray
def elekta_synergy_raw_lookup_table_image_filter(*args, **kwargs):
    """Procedural interface for ElektaSynergyRawLookupTableImageFilter"""
    import itk
    instance = itk.ElektaSynergyRawLookupTableImageFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def elekta_synergy_raw_lookup_table_image_filter_init_docstring():
    import itk
    import itkTemplate
    import itkHelpers
    if isinstance(itk.ElektaSynergyRawLookupTableImageFilter, itkTemplate.itkTemplate):
        filter_object = itk.ElektaSynergyRawLookupTableImageFilter.values()[0]
    else:
        filter_object = itk.ElektaSynergyRawLookupTableImageFilter

    elekta_synergy_raw_lookup_table_image_filter.__doc__ = filter_object.__doc__
    elekta_synergy_raw_lookup_table_image_filter.__doc__ += "\n Args are Input(s) to the filter.\n"
    elekta_synergy_raw_lookup_table_image_filter.__doc__ += "\n Available Keyword Arguments:\n"
    if isinstance(itk.ElektaSynergyRawLookupTableImageFilter, itkTemplate.itkTemplate):
        elekta_synergy_raw_lookup_table_image_filter.__doc__ += itkHelpers.filter_args(filter_object)[0]
        elekta_synergy_raw_lookup_table_image_filter.__doc__ += "\n"
        elekta_synergy_raw_lookup_table_image_filter.__doc__ += itkHelpers.filter_args(filter_object)[1]
    else:
        elekta_synergy_raw_lookup_table_image_filter.__doc__ += "".join([
            "  " + itkHelpers.camel_to_snake_case(item[3:]) + "\n"
            for item in dir(filter_object)
            if item.startswith("Set")])



