# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


from . import _RTKPython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rtkHisImageIOPython
else:
    import _rtkHisImageIOPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _rtkHisImageIOPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _rtkHisImageIOPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import itk.ITKIOImageBaseBasePython
import itk.ITKCommonBasePython
import itk.pyBasePython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.stdcomplexPython

def rtkHisImageIO_New():
    return rtkHisImageIO.New()

class rtkHisImageIO(itk.ITKIOImageBaseBasePython.itkImageIOBase):
    r"""Proxy of C++ rtkHisImageIO class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        r"""__init__(rtkHisImageIO self) -> rtkHisImageIO"""
        _rtkHisImageIOPython.rtkHisImageIO_swiginit(self, _rtkHisImageIOPython.new_rtkHisImageIO())
    __New_orig__ = _swig_new_static_method(_rtkHisImageIOPython.rtkHisImageIO___New_orig__)
    Clone = _swig_new_instance_method(_rtkHisImageIOPython.rtkHisImageIO_Clone)
    WriteImageInformation = _swig_new_instance_method(_rtkHisImageIOPython.rtkHisImageIO_WriteImageInformation)
    __swig_destroy__ = _rtkHisImageIOPython.delete_rtkHisImageIO
    cast = _swig_new_static_method(_rtkHisImageIOPython.rtkHisImageIO_cast)

    def New(*args, **kargs):
        """New() -> rtkHisImageIO

        Create a new object of the class rtkHisImageIO and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkHisImageIO.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkHisImageIO.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkHisImageIO.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkHisImageIO in _rtkHisImageIOPython:
_rtkHisImageIOPython.rtkHisImageIO_swigregister(rtkHisImageIO)
rtkHisImageIO___New_orig__ = _rtkHisImageIOPython.rtkHisImageIO___New_orig__
rtkHisImageIO_cast = _rtkHisImageIOPython.rtkHisImageIO_cast


def rtkHisImageIOFactory_New():
    return rtkHisImageIOFactory.New()

class rtkHisImageIOFactory(itk.ITKCommonBasePython.itkObjectFactoryBase):
    r"""Proxy of C++ rtkHisImageIOFactory class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkHisImageIOPython.rtkHisImageIOFactory___New_orig__)
    RegisterOneFactory = _swig_new_static_method(_rtkHisImageIOPython.rtkHisImageIOFactory_RegisterOneFactory)
    __swig_destroy__ = _rtkHisImageIOPython.delete_rtkHisImageIOFactory
    cast = _swig_new_static_method(_rtkHisImageIOPython.rtkHisImageIOFactory_cast)

    def New(*args, **kargs):
        """New() -> rtkHisImageIOFactory

        Create a new object of the class rtkHisImageIOFactory and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkHisImageIOFactory.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkHisImageIOFactory.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkHisImageIOFactory.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkHisImageIOFactory in _rtkHisImageIOPython:
_rtkHisImageIOPython.rtkHisImageIOFactory_swigregister(rtkHisImageIOFactory)
rtkHisImageIOFactory___New_orig__ = _rtkHisImageIOPython.rtkHisImageIOFactory___New_orig__
rtkHisImageIOFactory_RegisterOneFactory = _rtkHisImageIOPython.rtkHisImageIOFactory_RegisterOneFactory
rtkHisImageIOFactory_cast = _rtkHisImageIOPython.rtkHisImageIOFactory_cast



