# coding: utf-8

"""
    AristaFlowREST/WorklistManager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 4.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import af_worklist_manager
from af_worklist_manager.api.del_rec_remote_iterator_api import DelRecRemoteIteratorApi  # noqa: E501
from af_worklist_manager.rest import ApiException


class TestDelRecRemoteIteratorApi(unittest.TestCase):
    """DelRecRemoteIteratorApi unit test stubs"""

    def setUp(self):
        self.api = DelRecRemoteIteratorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_del_rec_drop(self):
        """Test case for del_rec_drop

        """
        pass

    def test_del_rec_get_next(self):
        """Test case for del_rec_get_next

        """
        pass

    def test_del_rec_get_previous(self):
        """Test case for del_rec_get_previous

        """
        pass

    def test_del_rec_keep_alive(self):
        """Test case for del_rec_keep_alive

        """
        pass


if __name__ == '__main__':
    unittest.main()
