from . import amazon
from . import bestbuy
from . import dell
from . import michaels
from . import acer
from . import walmart
from . import adafruit
from . import xbox
from . import joanns
from . import github_shop
from . import macys