# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


from . import _RTKPython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rtkPolynomialGainCorrectionImageFilterPython
else:
    import _rtkPolynomialGainCorrectionImageFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _rtkPolynomialGainCorrectionImageFilterPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _rtkPolynomialGainCorrectionImageFilterPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import itk.itkImageToImageFilterAPython
import itk.itkImagePython
import itk.itkRGBAPixelPython
import itk.itkFixedArrayPython
import itk.pyBasePython
import itk.itkSizePython
import itk.itkCovariantVectorPython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.stdcomplexPython
import itk.itkVectorPython
import itk.vnl_vector_refPython
import itk.itkRGBPixelPython
import itk.itkMatrixPython
import itk.vnl_matrix_fixedPython
import itk.itkPointPython
import itk.itkIndexPython
import itk.itkOffsetPython
import itk.ITKCommonBasePython
import itk.itkImageRegionPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkVectorImagePython
import itk.itkVariableLengthVectorPython
import itk.itkImageSourcePython
import itk.itkImageSourceCommonPython
import itk.itkImageToImageFilterCommonPython

def rtkPolynomialGainCorrectionImageFilterID3ID3_New():
    return rtkPolynomialGainCorrectionImageFilterID3ID3.New()

class rtkPolynomialGainCorrectionImageFilterID3ID3(itk.itkImageToImageFilterAPython.itkImageToImageFilterID3ID3):
    r"""Proxy of C++ rtkPolynomialGainCorrectionImageFilterID3ID3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterID3ID3___New_orig__)
    Clone = _swig_new_instance_method(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterID3ID3_Clone)
    SetDarkImage = _swig_new_instance_method(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterID3ID3_SetDarkImage)
    SetGainCoefficients = _swig_new_instance_method(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterID3ID3_SetGainCoefficients)
    SetK = _swig_new_instance_method(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterID3ID3_SetK)
    GetK = _swig_new_instance_method(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterID3ID3_GetK)
    __swig_destroy__ = _rtkPolynomialGainCorrectionImageFilterPython.delete_rtkPolynomialGainCorrectionImageFilterID3ID3
    cast = _swig_new_static_method(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterID3ID3_cast)

    def New(*args, **kargs):
        """New() -> rtkPolynomialGainCorrectionImageFilterID3ID3

        Create a new object of the class rtkPolynomialGainCorrectionImageFilterID3ID3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkPolynomialGainCorrectionImageFilterID3ID3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkPolynomialGainCorrectionImageFilterID3ID3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkPolynomialGainCorrectionImageFilterID3ID3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkPolynomialGainCorrectionImageFilterID3ID3 in _rtkPolynomialGainCorrectionImageFilterPython:
_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterID3ID3_swigregister(rtkPolynomialGainCorrectionImageFilterID3ID3)
rtkPolynomialGainCorrectionImageFilterID3ID3___New_orig__ = _rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterID3ID3___New_orig__
rtkPolynomialGainCorrectionImageFilterID3ID3_cast = _rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterID3ID3_cast


def rtkPolynomialGainCorrectionImageFilterIF3IF3_New():
    return rtkPolynomialGainCorrectionImageFilterIF3IF3.New()

class rtkPolynomialGainCorrectionImageFilterIF3IF3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    r"""Proxy of C++ rtkPolynomialGainCorrectionImageFilterIF3IF3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3___New_orig__)
    Clone = _swig_new_instance_method(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_Clone)
    SetDarkImage = _swig_new_instance_method(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_SetDarkImage)
    SetGainCoefficients = _swig_new_instance_method(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_SetGainCoefficients)
    SetK = _swig_new_instance_method(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_SetK)
    GetK = _swig_new_instance_method(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_GetK)
    __swig_destroy__ = _rtkPolynomialGainCorrectionImageFilterPython.delete_rtkPolynomialGainCorrectionImageFilterIF3IF3
    cast = _swig_new_static_method(_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_cast)

    def New(*args, **kargs):
        """New() -> rtkPolynomialGainCorrectionImageFilterIF3IF3

        Create a new object of the class rtkPolynomialGainCorrectionImageFilterIF3IF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkPolynomialGainCorrectionImageFilterIF3IF3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkPolynomialGainCorrectionImageFilterIF3IF3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkPolynomialGainCorrectionImageFilterIF3IF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkPolynomialGainCorrectionImageFilterIF3IF3 in _rtkPolynomialGainCorrectionImageFilterPython:
_rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_swigregister(rtkPolynomialGainCorrectionImageFilterIF3IF3)
rtkPolynomialGainCorrectionImageFilterIF3IF3___New_orig__ = _rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3___New_orig__
rtkPolynomialGainCorrectionImageFilterIF3IF3_cast = _rtkPolynomialGainCorrectionImageFilterPython.rtkPolynomialGainCorrectionImageFilterIF3IF3_cast


import itkHelpers
@itkHelpers.accept_numpy_array_like_xarray
def polynomial_gain_correction_image_filter(*args, **kwargs):
    """Procedural interface for PolynomialGainCorrectionImageFilter"""
    import itk
    instance = itk.PolynomialGainCorrectionImageFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def polynomial_gain_correction_image_filter_init_docstring():
    import itk
    import itkTemplate
    import itkHelpers
    if isinstance(itk.PolynomialGainCorrectionImageFilter, itkTemplate.itkTemplate):
        filter_object = itk.PolynomialGainCorrectionImageFilter.values()[0]
    else:
        filter_object = itk.PolynomialGainCorrectionImageFilter

    polynomial_gain_correction_image_filter.__doc__ = filter_object.__doc__
    polynomial_gain_correction_image_filter.__doc__ += "\n Args are Input(s) to the filter.\n"
    polynomial_gain_correction_image_filter.__doc__ += "\n Available Keyword Arguments:\n"
    if isinstance(itk.PolynomialGainCorrectionImageFilter, itkTemplate.itkTemplate):
        polynomial_gain_correction_image_filter.__doc__ += itkHelpers.filter_args(filter_object)[0]
        polynomial_gain_correction_image_filter.__doc__ += "\n"
        polynomial_gain_correction_image_filter.__doc__ += itkHelpers.filter_args(filter_object)[1]
    else:
        polynomial_gain_correction_image_filter.__doc__ += "".join([
            "  " + itkHelpers.camel_to_snake_case(item[3:]) + "\n"
            for item in dir(filter_object)
            if item.startswith("Set")])



