
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-24T17:12:00-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "00ab33767d051617defd9384eb808b250f999da6",
 "version": "0.0.4rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
