# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


from . import _RTKPython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _rtkDenoisingBPDQImageFilterPython
else:
    import _rtkDenoisingBPDQImageFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _rtkDenoisingBPDQImageFilterPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _rtkDenoisingBPDQImageFilterPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import itk.itkInPlaceImageFilterAPython
import itk.itkImageToImageFilterBPython
import itk.itkImageRegionPython
import itk.itkIndexPython
import itk.itkOffsetPython
import itk.itkSizePython
import itk.pyBasePython
import itk.ITKCommonBasePython
import itk.itkImageSourcePython
import itk.itkImagePython
import itk.itkRGBPixelPython
import itk.itkFixedArrayPython
import itk.stdcomplexPython
import itk.itkRGBAPixelPython
import itk.itkPointPython
import itk.vnl_vector_refPython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.itkVectorPython
import itk.itkCovariantVectorPython
import itk.itkMatrixPython
import itk.vnl_matrix_fixedPython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkImageSourceCommonPython
import itk.itkVectorImagePython
import itk.itkVariableLengthVectorPython
import itk.itkImageToImageFilterCommonPython
import itk.itkImageToImageFilterAPython

def rtkDenoisingBPDQImageFilterID2ICVF22_New():
    return rtkDenoisingBPDQImageFilterID2ICVF22.New()

class rtkDenoisingBPDQImageFilterID2ICVF22(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterID2ID2):
    r"""Proxy of C++ rtkDenoisingBPDQImageFilterID2ICVF22 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID2ICVF22___New_orig__)
    Clone = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID2ICVF22_Clone)
    GetNumberOfIterations = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID2ICVF22_GetNumberOfIterations)
    SetNumberOfIterations = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID2ICVF22_SetNumberOfIterations)
    SetGamma = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID2ICVF22_SetGamma)
    GetGamma = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID2ICVF22_GetGamma)
    __swig_destroy__ = _rtkDenoisingBPDQImageFilterPython.delete_rtkDenoisingBPDQImageFilterID2ICVF22
    cast = _swig_new_static_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID2ICVF22_cast)

    def New(*args, **kargs):
        """New() -> rtkDenoisingBPDQImageFilterID2ICVF22

        Create a new object of the class rtkDenoisingBPDQImageFilterID2ICVF22 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkDenoisingBPDQImageFilterID2ICVF22.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkDenoisingBPDQImageFilterID2ICVF22.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkDenoisingBPDQImageFilterID2ICVF22.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkDenoisingBPDQImageFilterID2ICVF22 in _rtkDenoisingBPDQImageFilterPython:
_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID2ICVF22_swigregister(rtkDenoisingBPDQImageFilterID2ICVF22)
rtkDenoisingBPDQImageFilterID2ICVF22___New_orig__ = _rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID2ICVF22___New_orig__
rtkDenoisingBPDQImageFilterID2ICVF22_cast = _rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID2ICVF22_cast


def rtkDenoisingBPDQImageFilterID3ICVF33_New():
    return rtkDenoisingBPDQImageFilterID3ICVF33.New()

class rtkDenoisingBPDQImageFilterID3ICVF33(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterID3ID3):
    r"""Proxy of C++ rtkDenoisingBPDQImageFilterID3ICVF33 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID3ICVF33___New_orig__)
    Clone = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID3ICVF33_Clone)
    GetNumberOfIterations = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID3ICVF33_GetNumberOfIterations)
    SetNumberOfIterations = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID3ICVF33_SetNumberOfIterations)
    SetGamma = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID3ICVF33_SetGamma)
    GetGamma = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID3ICVF33_GetGamma)
    __swig_destroy__ = _rtkDenoisingBPDQImageFilterPython.delete_rtkDenoisingBPDQImageFilterID3ICVF33
    cast = _swig_new_static_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID3ICVF33_cast)

    def New(*args, **kargs):
        """New() -> rtkDenoisingBPDQImageFilterID3ICVF33

        Create a new object of the class rtkDenoisingBPDQImageFilterID3ICVF33 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkDenoisingBPDQImageFilterID3ICVF33.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkDenoisingBPDQImageFilterID3ICVF33.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkDenoisingBPDQImageFilterID3ICVF33.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkDenoisingBPDQImageFilterID3ICVF33 in _rtkDenoisingBPDQImageFilterPython:
_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID3ICVF33_swigregister(rtkDenoisingBPDQImageFilterID3ICVF33)
rtkDenoisingBPDQImageFilterID3ICVF33___New_orig__ = _rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID3ICVF33___New_orig__
rtkDenoisingBPDQImageFilterID3ICVF33_cast = _rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterID3ICVF33_cast


def rtkDenoisingBPDQImageFilterIF2ICVF22_New():
    return rtkDenoisingBPDQImageFilterIF2ICVF22.New()

class rtkDenoisingBPDQImageFilterIF2ICVF22(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF2IF2):
    r"""Proxy of C++ rtkDenoisingBPDQImageFilterIF2ICVF22 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF2ICVF22___New_orig__)
    Clone = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF2ICVF22_Clone)
    GetNumberOfIterations = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF2ICVF22_GetNumberOfIterations)
    SetNumberOfIterations = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF2ICVF22_SetNumberOfIterations)
    SetGamma = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF2ICVF22_SetGamma)
    GetGamma = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF2ICVF22_GetGamma)
    __swig_destroy__ = _rtkDenoisingBPDQImageFilterPython.delete_rtkDenoisingBPDQImageFilterIF2ICVF22
    cast = _swig_new_static_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF2ICVF22_cast)

    def New(*args, **kargs):
        """New() -> rtkDenoisingBPDQImageFilterIF2ICVF22

        Create a new object of the class rtkDenoisingBPDQImageFilterIF2ICVF22 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkDenoisingBPDQImageFilterIF2ICVF22.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkDenoisingBPDQImageFilterIF2ICVF22.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkDenoisingBPDQImageFilterIF2ICVF22.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkDenoisingBPDQImageFilterIF2ICVF22 in _rtkDenoisingBPDQImageFilterPython:
_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF2ICVF22_swigregister(rtkDenoisingBPDQImageFilterIF2ICVF22)
rtkDenoisingBPDQImageFilterIF2ICVF22___New_orig__ = _rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF2ICVF22___New_orig__
rtkDenoisingBPDQImageFilterIF2ICVF22_cast = _rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF2ICVF22_cast


def rtkDenoisingBPDQImageFilterIF3ICVF33_New():
    return rtkDenoisingBPDQImageFilterIF3ICVF33.New()

class rtkDenoisingBPDQImageFilterIF3ICVF33(itk.itkInPlaceImageFilterAPython.itkInPlaceImageFilterIF3IF3):
    r"""Proxy of C++ rtkDenoisingBPDQImageFilterIF3ICVF33 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF3ICVF33___New_orig__)
    Clone = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF3ICVF33_Clone)
    GetNumberOfIterations = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF3ICVF33_GetNumberOfIterations)
    SetNumberOfIterations = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF3ICVF33_SetNumberOfIterations)
    SetGamma = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF3ICVF33_SetGamma)
    GetGamma = _swig_new_instance_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF3ICVF33_GetGamma)
    __swig_destroy__ = _rtkDenoisingBPDQImageFilterPython.delete_rtkDenoisingBPDQImageFilterIF3ICVF33
    cast = _swig_new_static_method(_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF3ICVF33_cast)

    def New(*args, **kargs):
        """New() -> rtkDenoisingBPDQImageFilterIF3ICVF33

        Create a new object of the class rtkDenoisingBPDQImageFilterIF3ICVF33 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          rtkDenoisingBPDQImageFilterIF3ICVF33.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = rtkDenoisingBPDQImageFilterIF3ICVF33.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = rtkDenoisingBPDQImageFilterIF3ICVF33.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register rtkDenoisingBPDQImageFilterIF3ICVF33 in _rtkDenoisingBPDQImageFilterPython:
_rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF3ICVF33_swigregister(rtkDenoisingBPDQImageFilterIF3ICVF33)
rtkDenoisingBPDQImageFilterIF3ICVF33___New_orig__ = _rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF3ICVF33___New_orig__
rtkDenoisingBPDQImageFilterIF3ICVF33_cast = _rtkDenoisingBPDQImageFilterPython.rtkDenoisingBPDQImageFilterIF3ICVF33_cast


import itkHelpers
@itkHelpers.accept_numpy_array_like_xarray
def denoising_bpdq_image_filter(*args, **kwargs):
    """Procedural interface for DenoisingBPDQImageFilter"""
    import itk
    instance = itk.DenoisingBPDQImageFilter.New(*args, **kwargs)
    return instance.__internal_call__()

def denoising_bpdq_image_filter_init_docstring():
    import itk
    import itkTemplate
    import itkHelpers
    if isinstance(itk.DenoisingBPDQImageFilter, itkTemplate.itkTemplate):
        filter_object = itk.DenoisingBPDQImageFilter.values()[0]
    else:
        filter_object = itk.DenoisingBPDQImageFilter

    denoising_bpdq_image_filter.__doc__ = filter_object.__doc__
    denoising_bpdq_image_filter.__doc__ += "\n Args are Input(s) to the filter.\n"
    denoising_bpdq_image_filter.__doc__ += "\n Available Keyword Arguments:\n"
    if isinstance(itk.DenoisingBPDQImageFilter, itkTemplate.itkTemplate):
        denoising_bpdq_image_filter.__doc__ += itkHelpers.filter_args(filter_object)[0]
        denoising_bpdq_image_filter.__doc__ += "\n"
        denoising_bpdq_image_filter.__doc__ += itkHelpers.filter_args(filter_object)[1]
    else:
        denoising_bpdq_image_filter.__doc__ += "".join([
            "  " + itkHelpers.camel_to_snake_case(item[3:]) + "\n"
            for item in dir(filter_object)
            if item.startswith("Set")])



